//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">柳河简介</p>`,
		text1: `<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 15.75pt;">柳河县地处吉林省东南部，幅员面积<span lang="EN-US">3348</span>平方公里，辖<span lang="EN-US">15</span>个乡镇，<span lang="EN-US">3</span>个街道，<span lang="EN-US">219</span>个行政村，总人口<span lang="EN-US">38</span>万。区位优势明显，通化三源浦机场直飞北京、上海等城市；通梅、鹤大等三条高速公路在柳河交汇，四平至二道白河高铁项目加快推进，柳河已经成为空中交通始发地、高速公路集结点和陆路干港结合部。森林覆盖率达<span lang="EN-US">51.49%</span>，年平均水资源总量<span lang="EN-US">11.22</span>亿立方米，探明金、铁等矿藏资源达<span lang="EN-US">31</span>种。是国家商品粮基地县，全国粮食生产先进县，中国绿色名县，国家级山葡萄生产标准化示范区，中国山葡萄酒之乡，中国火山岩稻米之乡，中国民间文化艺术之乡，全国全民健身活动先进县，吉林省最大的烟叶生产基地，全国首家造林苗木交易市场，中国书法之乡，国家级卫生县城，全国双拥模范县，全国百佳乡村旅游目的地，全国<span lang="EN-US">&ldquo;</span>四好<span lang="EN-US">&rdquo;</span>农村路建设示范县，省级文明城、园林城和生态城。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US">2022</span>年，柳河县委将以习近平新时代中国特色社会主义思想为指引，按照省<span lang="EN-US">&ldquo;</span>一主、六双<span lang="EN-US">&rdquo;</span>产业空间布局部署要求，深入落实市<span lang="EN-US">&ldquo;</span>集中攻坚行动<span lang="EN-US">&rdquo;</span>，坚持稳中求进工作总基调，打造新发展优势，做大做强战略新兴、医药健康、旅游休闲、特色农业和现代服务<span lang="EN-US">&ldquo;</span>五大主导优势产业<span lang="EN-US">&rdquo;</span>，加快实现新时代柳河高质量发展。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.1pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span><span style="font-family: 宋体; mso-bidi-font-family: 宋体;">一是医药健康产业。</span></span></strong>全县共有医药生产企业<span lang="EN-US">12</span>家，<span lang="EN-US">94</span>条生产线、<span lang="EN-US">21</span>个剂型、<span lang="EN-US">604</span>个医药品种（单品种销售收入超百万元<span lang="EN-US">17</span>个；超亿元<span lang="EN-US">2</span>个，为修正肺宁颗粒和紫鑫四妙丸）。<span lang="EN-US">2019</span>年实现产值<span lang="EN-US">12.1</span>亿元，增长<span lang="EN-US">17%</span>；利润<span lang="EN-US">2.2</span>亿元，增长<span lang="EN-US">10%</span>；税金<span lang="EN-US">1.7</span>亿元，增长<span lang="EN-US">15%</span>。对接长辽梅通白敦医药健康产业走廊，建设集生产示范、精深加工、产品销售、文化旅游、养生养老于一体的人参产业特色小镇和医药健康产业集群。重点推进经济开发区大健康产业园标准化厂房项目，筑巢引凤，高质量打造建设医药食品和加工制造项目承载平台。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.1pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span><span style="font-family: 宋体; mso-bidi-font-family: 宋体;">二是旅游休闲产业。</span></span></strong>柳河是<span lang="EN-US">&ldquo;</span>全国百佳乡村旅游目的地<span lang="EN-US">&rdquo;</span>，<span lang="EN-US">3A</span>级景区<span lang="EN-US">6</span>家，<span lang="EN-US">2A</span>级景区<span lang="EN-US">1</span>家，省级自然保护区<span lang="EN-US">1</span>处，国家级森林公园<span lang="EN-US">1</span>处。围绕<span lang="EN-US">&ldquo;</span>一核一带一点一线一环<span lang="EN-US">&rdquo;&ldquo;</span>五个一<span lang="EN-US">&rdquo;</span>全域旅游格局建设，重点推进投资<span lang="EN-US">115</span>亿元的<span lang="EN-US">MVR</span>世博村青龍山滑雪场度假区项目，投资<span lang="EN-US">8</span>亿元的沈阳珩阳逸景罗通山康养小镇项目，投资<span lang="EN-US">6.5</span>亿元别有洞天红色旅游景区，投资<span lang="EN-US">5</span>亿元的罗通山旅游度假区项目，投资<span lang="EN-US">3</span>亿元的丽景国际大酒店等项目，深度谋划桃花湖、梨花谷、梅花洲、参谷雪乡、田园枫谷等旅游节点项目。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.1pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span><span style="font-family: 宋体; mso-bidi-font-family: 宋体;">三是特色农业。</span></span></strong>稻米产业方面，共有水稻种植面积<span lang="EN-US">32</span>万亩，其中绿色稻米<span lang="EN-US">8.62</span>万亩，稻米加工企业<span lang="EN-US">23</span>户，年加工能力<span lang="EN-US">45</span>万吨。山葡萄产业方面，山葡萄种植面积<span lang="EN-US">1.2</span>万亩，山葡萄酒企业<span lang="EN-US">23</span>户，葡萄酒生产线<span lang="EN-US">50</span>余条，年产量约<span lang="EN-US">2.3</span>万吨、产值<span lang="EN-US">1.8</span>亿元。中药材产业方面，全县发展各类中小药材近<span lang="EN-US">20</span>个品种，面积<span lang="EN-US">4.6</span>万亩，产量<span lang="EN-US">5184</span>吨，产值<span lang="EN-US">1.2</span>亿元。烟叶产业方面，种植面积<span lang="EN-US">1.6</span>万亩，产值<span lang="EN-US">6000</span>万元，税收<span lang="EN-US">2300</span>万元。特色林果产业方面，大榛子、寒富苹果、蓝莓等林果种植面积达到<span lang="EN-US">8.5</span>万亩，产量<span lang="EN-US">1.5</span>万吨。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.1pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span><span style="font-family: 宋体; mso-bidi-font-family: 宋体;">四是现代服务业。</span></span></strong>我县有商贸主体<span lang="EN-US">9503</span>个，其中限额以上商贸企业<span lang="EN-US">23</span>个。我县是国家电子商务进农村综合示范县，位列全国农产品电商<span lang="EN-US">50</span>强县的第<span lang="EN-US">34</span>位。积极培育投资<span lang="EN-US">5</span>亿元以上的衍庶街滨水文旅特色商业圈，重点推动投资<span lang="EN-US">3</span>亿元的香颂电商旅游街项目，投资<span lang="EN-US">3</span>亿元的盛鹏大唐景象项目，投资<span lang="EN-US">2.8</span>亿元的京东物流项目、投资<span lang="EN-US">1.4</span>亿元的京东商城建设项目。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.1pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span><span style="font-family: 宋体; mso-bidi-font-family: 宋体;">五是战略新兴产业。</span></span></strong>重点推动总投资近百亿元的中溢科技集团年产<span lang="EN-US">16</span>万吨大规格超高功率石墨电极项目和年产<span lang="EN-US">10</span>万吨锂离子电池负极材料项目，着力建设新能源、新材料产业增长极。总投资百亿元以上的风电、光伏、抽水蓄能、林业碳汇等全域清洁能源综合开发项目，打造绿色循环的县域经济发展新模式。</p>
<p style="text-align: justify; text-justify: inter-ideograph; text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;">千年古城百年县，一城柳绿半城河，生机焕发、充满活力的柳河欢迎您！</p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
