//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">柳河开发区</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">柳河经济开发区组建于<span lang="EN-US">2005</span>年<span lang="EN-US">9</span>月，<span lang="EN-US">2018</span>年<span lang="EN-US">6</span>月进入国家开发区目录，<span lang="EN-US">2020</span>年<span lang="EN-US">7</span>月<span lang="EN-US">14</span>日晋级省级开发区，规划总面积<span lang="EN-US">12</span>平方公里，建成区面积<span lang="EN-US">5.8</span>平方公里，现居住人口<span lang="EN-US">15480</span>人，曾连续五年被评为省级先进。四至范围为东至集双高速柳河北出口，西至柳河镇长青路，南至通梅公路小五道路口处，北至柳梅分界岭。园区区位优势明显，通梅一级公路、通梅高速公路、梅集铁路在区中穿过，距离通化三源浦机场<span lang="EN-US">28</span>公里。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">柳河经济开发区地块完整，建设预留地充裕，建有孵化产业园<span lang="EN-US">40</span>万平，适合各类企业前来投资。柳河经济开发区曾连续五年被评为省级先进，其中<span lang="EN-US">2015</span>年和<span lang="EN-US">2016</span>年在全省同类<span lang="EN-US">78</span>个开发区综合工作考核中荣获一等奖，是这个奖项自建立以来唯一连续两年获奖的开发区。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">&ldquo;十四五&rdquo;期间，开发区全面实施<span lang="EN-US">1124</span>战略：</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;"><strong>&ldquo;<span lang="EN-US">1</span>&rdquo;是坚持一个核心：</strong>始终坚持以高质量发展为核心；推进一个达到：规划期末工业总产值达百亿元；</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;"><strong>&ldquo;<span lang="EN-US">2</span>&rdquo;是打造二个国家级基地：</strong>打造国家级新材料工业基地、国家级医药健康产业基地；</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;"><strong>&ldquo;<span lang="EN-US">4</span>&rdquo;是建设四大产业体系：</strong>战略新产业体系、医药健康产业体系、绿色食品加工体系、现代服务业体系。形成&ldquo;一心一镇四园&rdquo;的空间发展格局<span lang="EN-US">,</span>即：科技创新中心，参业小镇，大健康产业园、新材料产业园、绿色食品产业园、现代物流产业园。坚持&ldquo;绿色、低碳、循环、跨越&rdquo;的发展理念，力争跻身吉林省省级开发区前列。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">目前，开发区落户企业<span lang="EN-US">55</span>户<span lang="EN-US">(</span>其中，生产企业<span lang="EN-US">27</span>户、停产、半停产、季节性生产企业<span lang="EN-US">18</span>户，新建续建企业<span lang="EN-US">10</span>户<span lang="EN-US">)</span>，投资超亿元的企业<span lang="EN-US">26</span>户，规模以上企业<span lang="EN-US">13</span>户，其中紫鑫、天强、龙泰、中晟<span lang="EN-US">4</span>户为高新技术企业，省级葡萄酒研发中心<span lang="EN-US">1</span>户。已征收土地<span lang="EN-US">292.88</span>公顷，办理征转用土地<span lang="EN-US">114.02</span>公顷（完成供地<span lang="EN-US">65.82</span>公顷），已征未转土地<span lang="EN-US">178.86</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">2019</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">年<span lang="EN-US">,</span>完成工业产值<span lang="EN-US">21.29</span>亿元，销售收入<span lang="EN-US">19.37</span>亿元<span lang="EN-US">,</span>税收<span lang="EN-US">1.99</span>亿元。<span lang="EN-US">2020</span>年受疫情影响，完成工业产值<span lang="EN-US">20.18</span>亿元，销售收入<span lang="EN-US">14.53</span>亿元，税收<span lang="EN-US">0.7</span>亿元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast; mso-bidi-font-family: 宋体; color: black; mso-font-kerning: 0pt;">截止<span lang="EN-US">2021</span>年上半年，区内完成工业产值<span lang="EN-US">12.2</span>亿元，同比增长<span lang="EN-US">9.13%</span>；销售收入<span lang="EN-US">8.06</span>亿元；税收<span lang="EN-US">4936</span>万元<span lang="EN-US">,</span>同比增长<span lang="EN-US">39.22%</span>。全区从业人数为<span lang="EN-US">2701</span>人。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
