//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">医药健康产业</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><a name="_Toc56757225"></a><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、产业概况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="mso-bookmark: _Toc56757225;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县现有医药生产企业<span lang="EN-US">12</span>家，其中规模以上企业<span lang="EN-US">9</span>家。生产中成药<span lang="EN-US">11</span>家，化药<span lang="EN-US">1</span>家，上市企业<span lang="EN-US">1</span>家（紫鑫药业）。龙头企业以紫鑫药业、长隆制药、天强制药、龙泰制药为主要代表企业。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">12.31</span>亿元，占比规上工业企业产值<span lang="EN-US">50%</span>以上；上缴税金<span lang="EN-US">4906</span>万元，占全县规上工业企业上缴税金<span lang="EN-US">76%</span>。</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="mso-bookmark: _Toc56757225;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在企业研发平台建设方面：拥有研发中心<span lang="EN-US">2</span>个（紫鑫药业&ldquo;吉林省中医药研究室&rdquo;、钓鱼台医药集团吉林天强制药与中国中医科学院合作的中医实验中心）、高新技术企业<span lang="EN-US">4</span>户、科技小巨人企业<span lang="EN-US">2</span>户、市级以上技术中心<span lang="EN-US">4</span>个。</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="mso-bookmark: _Toc56757225;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在企业品牌能力建设方面：拥有国家级驰名商标<span lang="EN-US">1</span>个、省级著名商标<span lang="EN-US">6</span>个、吉林名牌<span lang="EN-US">11</span>个。</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="mso-bookmark: _Toc56757225;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在企业生产药品品种方面：拥有<span lang="EN-US">678</span>个文号、<span lang="EN-US">614</span>个品种、<span lang="EN-US">84</span>条生产线、<span lang="EN-US">21</span>个剂型。</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、规模以上医药产业企业简介</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）吉林紫鑫药业股份有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">1998</span>年<span lang="EN-US">5</span>月，注册资金为<span lang="EN-US">12.8</span>亿元，公司位于柳河经济开发区，占地面积<span lang="EN-US">22</span>万平方米，建筑面积<span lang="EN-US">10.7</span>万平方米，现有员工<span lang="EN-US">651</span>人。<span lang="EN-US">2007</span>年<span lang="EN-US">3</span>月在深交所挂牌上市，公司<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">6.56</span>亿元，是一家集中成药研发、生产、销售，饮片加工，药用动植物种养殖为一体的省级高新科技企业。公司现有<span lang="EN-US">12</span>个剂型，<span lang="EN-US">129</span>个品种的产品中，&ldquo;紫鑫牌四妙丸&rdquo;、&ldquo;醒脑再造胶囊&rdquo;、&ldquo;活血通脉片&rdquo;、&ldquo;复方益肝灵片&rdquo;、&ldquo;藿胆片&rdquo;等<span lang="EN-US">5</span>个品种被列为国家二级中药保护品种；有<span lang="EN-US">32</span>个品种列入国家基本药目录，<span lang="EN-US">28</span>个品种进入吉林省基本药目录。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）柳河长隆制药有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">2018</span>年，为修正药业集团下属子公司，注册资金为<span lang="EN-US">1000</span>万元。公司位于柳河镇迎宾路，现有员工<span lang="EN-US">352</span>人。主要经营范围为：硬胶囊剂制造、销售及出口业务；片剂、颗粒剂制造与销售；中药材提取与收购。公司拥有肺宁颗粒、贞芪扶正颗粒、保心宁片等<span lang="EN-US">17</span>个品种。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">1.8</span>亿元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）吉林龙泰制药股份有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">2002</span>年<span lang="EN-US">4</span>月，注册资金为<span lang="EN-US">5000</span>万元。公司位于柳河镇站前路，占地面积<span lang="EN-US">42000</span>平方米，建筑面积<span lang="EN-US">25000</span>平方米，现有员工<span lang="EN-US">311</span>人。龙泰是一家集科研、开发、生产、营销为一体的省级高新技术企业，主要从事中成药、针剂的生产研发。公司拥有<span lang="EN-US">12</span>个剂型、<span lang="EN-US">149</span>个国药准字号品种，主要产品有：益气养血口服液、荨麻疹丸、风寒感冒颗粒等。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">8402</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（四）柳河正通药业有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">2002</span>年<span lang="EN-US">5</span>月，是修正药业集团产业总公司下属子公司，注册资金<span lang="EN-US">100</span>万元。公司位于柳河经济开发区，占地面积<span lang="EN-US">68598</span>平方米，建筑面积<span lang="EN-US">47362</span>平方米，现有员工<span lang="EN-US">123</span>人。主要产品是为修正药业集团产业总公司生产加工、提取中药半成品和饮片加工、销售、提供基础原料药的一家民营企业。公司公司主要产品有：肺宁颗粒、贞芪扶正颗粒、炎可宁片。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">3779</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（五）修正药业集团柳河制药有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">2000</span>年<span lang="EN-US">7</span>月，公司位于柳河镇修正路，注册资本<span lang="EN-US">300</span>万元。公司占地面积<span lang="EN-US">1.9</span>万平方米，建筑面积<span lang="EN-US">1.05</span>万平方米，现有员工<span lang="EN-US">140</span>人。公司主要生产剂型为原料药，是生产原料药的专业公司，产品销往国内外，为国内外各医药企业提供配套的原料药产品和中间体。主要品种有盐酸吗啉胍、厄贝沙坦、加替沙星、盐酸伊托必利、盐酸特比萘芬等<span lang="EN-US">9</span>个品种。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">6827</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（六）吉林省中晟制药有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">2012</span>年，，隶属于广东大光投资集团有限公司，注册资金为<span lang="EN-US">3000</span>万元。公司位于柳河经济开发区，占地面积<span lang="EN-US">120</span>亩，建筑面积<span lang="EN-US">2.5</span>万平方米，拥有各类技术人员<span lang="EN-US">70</span>人。公司以生产中药为主，有片剂、胶囊、颗粒剂等现代剂型，公司拥有<span lang="EN-US">4</span>个剂型，<span lang="EN-US">41</span>个文号，<span lang="EN-US">38</span>个品种。主要产品有：&ldquo;蛹虫草菌粉胶囊&rdquo;、&ldquo;痹欣片&rdquo;等，其中独家品种有三项，国家一类新药一项，国家专利产品一项。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">6747</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（七）吉林天强制药股份有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司成立于<span lang="EN-US">1999</span>年<span lang="EN-US">9</span>月，注册资金<span lang="EN-US">3600</span>万元。公司位于柳河县经济开发区，占地面积<span lang="EN-US">4.7</span>万平方米，建筑面积<span lang="EN-US">2.6</span>万平方米拥有员工<span lang="EN-US">350</span>人。公司经营范围主要有：中西药制剂、原料药、保健食品、空心胶囊、葡萄酒生产、中药材种植、梅花鹿饲养等，主要剂型有片剂、丸剂（水蜜丸、大蜜丸）、胶囊剂、煎膏剂、颗粒剂、合剂（含口服液），原料药以及保健品等九个剂型。公司主要产品&ldquo;舒筋胶囊&rdquo;为独家品种，&ldquo;麝香抗栓丸&rdquo;为国家中药保护品种。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">6430</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（八）通化仁民药业股份有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司始建于<span lang="EN-US">1978</span>年，注册资金<span lang="EN-US">6008</span>万元。公司位于柳河县长青路<span lang="EN-US">50</span>号，占地面积<span lang="EN-US">2.9</span>万平方米，建筑面积<span lang="EN-US">1.5</span>万平方米，现有员工<span lang="EN-US">116</span>人。公司生产主导品种有&ldquo;风热感冒颗粒&rdquo;、&ldquo;头孢氨苄甲氧苄啶胶囊&rdquo;、&ldquo;五加参蛤蚧精&rdquo;、&ldquo;鸦胆子油口服乳液&rdquo;、&ldquo;参术儿康糖浆&rdquo;、&ldquo;脑力宝丸&rdquo;、&ldquo;曲咪新乳膏&rdquo;等。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">3402</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（九）通化斯威药业股份有限公司</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">该公司始建于<span lang="EN-US">2001</span>年，注册资本<span lang="EN-US">3033</span>万元。公司位于柳河镇斯威路<span lang="EN-US">1</span>号，占地面积<span lang="EN-US">3.2</span>万平方米，建筑面积<span lang="EN-US">2.1</span>万平方米，现有员工<span lang="EN-US">135</span>人。公司现有片剂、胶囊剂、颗粒剂<span lang="EN-US">3</span>个剂型、<span lang="EN-US">32</span>个药品品种，产品批准文号<span lang="EN-US">31</span>个。公司主要产品&ldquo;前列舒乐胶囊&rdquo;获得国家级新药证书和国家知识产权局颁发的专利证书。<span lang="EN-US">2020</span>年实现产值<span lang="EN-US">3735</span>万元。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
