//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">现代服务业</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、电商发展基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2015</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年我县被评为省级电商示范县；<span lang="EN-US">2016</span>年我县被商务部评为&ldquo;全国第三批电子商务进农村综合示范县&rdquo;；<span lang="EN-US">2017</span>年<span lang="EN-US">5</span>月<span lang="EN-US">5</span>日，阿里研究院基于农产品销售额排名，发布了农产品电商<span lang="EN-US">50</span>强县，其中我县位列全国第<span lang="EN-US">34</span>位<span lang="EN-US">;2019</span>年，我县被列为全省城乡高效配送第一批试点县。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">截至目前<span lang="EN-US">,</span>县内网商总数<span lang="EN-US">2200</span>余家，物流快递企业<span lang="EN-US">20</span>余家，创建电商集聚区<span lang="EN-US">2</span>个，入驻电商相关企业<span lang="EN-US">60</span>余家，电商带动就业<span lang="EN-US">8200</span>余人，培育了大米姐恒通专卖店、大米姐旗舰店、长白山特产专营店、吉品汇食品专营店、优峰酒类专营店等本地优秀网商。随着电商产业不断发展，已经推动了全县产业结构调整。近几年来，我县积极培育了&ldquo;柳河县火山岩稻米、柳河山葡萄酒、安口镇苗木、安口镇大榛子、向阳苹果、红石人参、柳河镇水果（苹果梨、南果梨、草莓、蓝莓）、凉水山货&rdquo;等八大特色产业基地。柳河大米、山葡萄酒、大榛子、人参、蓝莓等产品已成为网上热销商品。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2020</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年我县实现电商交易额<span lang="EN-US">23</span>亿元，同比增长<span lang="EN-US">6.8%</span>；实现网络零售额<span lang="EN-US">5.8</span>亿元，同比增长<span lang="EN-US">11.93</span>℅；实现农产品网络零售额<span lang="EN-US">1.34</span>亿元，同比增长<span lang="EN-US">52.27</span>℅。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、全县市场经营户整体状况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">截止<span lang="EN-US">2020</span>年，我县共有市场主体<span lang="EN-US">24340</span>户，其中个体工商户<span lang="EN-US">19148</span>户，私营企业<span lang="EN-US">3244</span>户，农民专业合作社<span lang="EN-US">1557</span>户，内资企业<span lang="EN-US">391</span>户。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、大型商超、农贸市场等整体内贸情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县内共有<span lang="EN-US">2</span>个成型农贸市场，其中柳河县农贸大厅位于柳河中心商圈步行街内，为混合所有性企业，作为镇内最大农贸市场，基础设施功能较全、辐射较广，经营面积<span lang="EN-US">1200</span>平方米，年交易额<span lang="EN-US">8000</span>万元。另有位于柳河中心商圈的鑫丰源、农鲜园、宏福三家大型超市，以租赁经营模式开展运营，主要经营品类为水果、蔬菜等生鲜食品。其中：鑫丰源超市（含汇美佳超市）经营面积<span lang="EN-US">1000</span>平方米，年交易额约为<span lang="EN-US">1400</span>万元；农鲜园超市经营面积<span lang="EN-US">1300</span>平方米，年交易额约为<span lang="EN-US">1000</span>万元；宏福超市经营面积<span lang="EN-US">1300</span>平方米，年交易额约为<span lang="EN-US">500</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、大型商贸项目建设情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">我县为加快现代服务业发展，推动创业，改善民生环境。<span lang="EN-US">2019</span>年以来，县委、县政府先后引进了京东商城、香颂电商旅游街及盛鹏大唐景象项目。项目建成后，将形成商贸、文娱、电商于一体的现代服务业综合体。项目将采用京东、阿里、拼多多等平台线上线下一体化模式，解决区域消费需求，带动柳河农特产品线上销售，助力全县特色富民产业加速发展。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">京东商城项目，项目位于柳河县北部新城区，总投资<span lang="EN-US">2</span>亿元，占地面积<span lang="EN-US">1.83</span>万平方米，建筑面积<span lang="EN-US">1.8</span>万平方米。项目投产达效后，预计可实现年产值<span lang="EN-US">2</span>亿元，带动就业约<span lang="EN-US">200</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">香颂电商旅游街项目，项目位于县城西部、衍庶街西北方向，总投资<span lang="EN-US">3.06</span>亿元，占地<span lang="EN-US">5.27</span>万平方米，建筑面积<span lang="EN-US">5.03</span>万平方米。项目投产达效后，预计可实现年产值<span lang="EN-US">2</span>亿元，带动就业约<span lang="EN-US">500</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">盛鹏大唐景象项目，项目位于县城西部，衍庶街东北方向，总投资<span lang="EN-US">3.16</span>亿元，占地面积<span lang="EN-US">5.2</span>万平方米，建筑面积<span lang="EN-US">4.8</span>万平方米。项目投产达效后，预计可实现年产值<span lang="EN-US">1.6</span>亿元，带动就业约<span lang="EN-US">300</span>人。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
