//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text2: `<p style="text-align: center;">战略新兴产业</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 28.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 仿宋_GB2312;">柳河县战略新兴产业主要分为三大板块，一是以吉林中溢炭素年产<span lang="EN-US">30</span>万吨超高功率石墨电极项目和年产<span lang="EN-US">30</span>万吨智能汽车锂离子电池负极材料项目为产业主导的新材料板块；二是以柳河工业集中区大健康产业园区（标准厂房）建设项目为平台依托的工业孵化器板块；三是以&ldquo;风、光、水&rdquo;电力开发为主的清洁能源板块。</span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 28.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">一、新材料产业</span></p>
<p class="MsoNormal" style="text-indent: 32pt; line-height: 28pt;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">柳河县新材料产业园位于柳河经济开发区东南部，园区占地面积约</span><span lang="EN-US">2500</span><span style="font-family: 仿宋_GB2312;">亩，区内的省级龙头企业、国家高新科技企业中溢集团（吉林）新能源科技有限公司成立于</span><span lang="EN-US">2019</span><span style="font-family: 仿宋_GB2312;">年</span><span lang="EN-US">5</span><span style="font-family: 仿宋_GB2312;">月，是专业从事新能源电池负极材料、大规格超高功率石墨电极、石墨制品等产品研发、生产、销售的大型生产企业，也是石墨电极行业生产规模排名前列、单体全流程生产规模排名第一位的生产企业。公司占地面积</span><span lang="EN-US">1850</span><span style="font-family: 仿宋_GB2312;">亩，建筑面积</span><span lang="EN-US">65</span><span style="font-family: 仿宋_GB2312;">万平方米，拥有员工</span><span lang="EN-US">2000</span><span style="font-family: 仿宋_GB2312;">人。近年来，公司先后投资</span><span lang="EN-US">100</span><span style="font-family: 仿宋_GB2312;">亿元，建设了有年产</span><span lang="EN-US">30</span><span style="font-family: 仿宋_GB2312;">万吨新能源电池负极材料项目、年产</span><span lang="EN-US">30</span><span style="font-family: 仿宋_GB2312;">万吨大规格超高功率石墨电极及石墨制品项目。项目建成达产后，年销售收入</span><span lang="EN-US">300</span><span style="font-family: 仿宋_GB2312;">亿元，年税收</span><span lang="EN-US">30</span><span style="font-family: 仿宋_GB2312;">亿元，年利润</span><span lang="EN-US">50</span><span style="font-family: 仿宋_GB2312;">亿元，具有良好的经济效益和社会效益。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">目前，公司生产的锂离子电池人造石墨负极材料是为电动汽车等交通工具、工业储能、</span><span lang="EN-US">3C</span><span style="font-family: 仿宋_GB2312;">消费电子等领域提供电源的电池核心材料。项目达标后，生产的锂电池负极材料</span><span lang="EN-US">80%</span><span style="font-family: 仿宋_GB2312;">销往国内锂电池制造厂，</span><span lang="EN-US">20%</span><span style="font-family: 仿宋_GB2312;">销往东亚、欧洲、美国等国家和地区。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">公司生产的大规格超高功率石墨电极及石墨制品是为国内外钢铁冶炼、非金属冶炼及负极材料生产配套的循环经济产业项目。项目的主导产品为直径</span><span lang="EN-US">600</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">800mm</span><span style="font-family: 仿宋_GB2312;">石墨电极、石墨炭砖、石墨质坩埚、石墨坩埚、石墨板、石墨异形件等石墨制品，产品采用国内外优质针状焦、石油焦为原料，煤沥青作粘合剂，经科学配方精工制造而成。公司石墨电极及石墨制品除销往国内大型钢厂等应用行业外，还销往欧美、东南亚、非洲等多个国家和地区。项目投产后，计划</span><span lang="EN-US">60%</span><span style="font-family: 仿宋_GB2312;">的产品供国内市场，</span><span lang="EN-US">40%</span><span style="font-family: 仿宋_GB2312;">的产品供国外市场。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">二、工业园区孵化器</span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">柳河工业集中区大健康产业园区（标准厂房）建设项目项目位于柳河经济开发区内，东临空军导航台，南临园区五路，西临空地、北临一统河。项目总投资</span><span lang="EN-US">9.7</span><span style="font-family: 仿宋_GB2312;">亿元，总占地约</span><span lang="EN-US">652</span><span style="font-family: 仿宋_GB2312;">亩，建筑面积</span><span lang="EN-US">35.15</span><span style="font-family: 仿宋_GB2312;">万平方米。园内设有</span><span lang="EN-US">ABCDE</span><span style="font-family: 仿宋_GB2312;">五个区域，包括标准化厂房</span><span lang="EN-US">41</span><span style="font-family: 仿宋_GB2312;">栋、仓库</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">栋、综合楼</span><span lang="EN-US">5</span><span style="font-family: 仿宋_GB2312;">栋、门卫等附属用房</span><span lang="EN-US">16</span><span style="font-family: 仿宋_GB2312;">栋以及园区给排水、供热、供电、通信管线等公用工程的建设。园区厂房主要为</span><span lang="EN-US">2</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">3</span><span style="font-family: 仿宋_GB2312;">层框架混凝土结构建筑为主。平均每层建筑面积约</span><span lang="EN-US">3000</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">4000</span><span style="font-family: 仿宋_GB2312;">平米，厂房建筑平均举架净高约</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">米。适宜开展设备组装、食药品加工、材料加工等类型项目。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">目前，入驻柳河经济开发区大健康产业园区标准厂房费用标准拟定在每平方米每年</span><span lang="EN-US">140</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">160</span><span style="font-family: 仿宋_GB2312;">元，入驻企业根据项目投资规模可享受</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">12</span><span style="font-family: 仿宋_GB2312;">个月免费装修改造优惠。另外，为进一步深入推进产业结构调整和经济转型升级，鼓励优秀企业入驻标准厂房，柳河县将在入驻企业厂房租金、厂房改造升级、项目建设等方面予以补贴和扶持。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">三、清洁能源产业</span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">柳河县地处</span><span lang="EN-US"><a href="https://baike.baidu.com/item/%E9%95%BF%E7%99%BD%E5%B1%B1/9596?fromModule=lemma_inlink" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E5%8E%BF/_blank"><span lang="EN-US" style="font-family: 仿宋_GB2312; color: windowtext;">长白山</span></a></span><span style="font-family: 仿宋_GB2312;">向</span><span lang="EN-US"><a href="https://baike.baidu.com/item/%E6%9D%BE%E8%BE%BD%E5%B9%B3%E5%8E%9F/6099032?fromModule=lemma_inlink" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E5%8E%BF/_blank"><span lang="EN-US" style="font-family: 仿宋_GB2312; color: windowtext;">松辽平原</span></a></span><span style="font-family: 仿宋_GB2312;">过渡地带，森林覆盖率高达</span><span lang="EN-US">51%</span><span style="font-family: 仿宋_GB2312;">，生态环境良好。经专业机构测算，雨水、光照、风力等气象资源丰富，年均</span><span lang="EN-US"><a href="https://baike.baidu.com/item/%E9%99%8D%E6%B0%B4%E9%87%8F/850460?fromModule=lemma_inlink" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E5%8E%BF/_blank"><span lang="EN-US" style="font-family: 仿宋_GB2312; color: windowtext;">降水量</span></a></span><span style="font-family: 仿宋_GB2312;">约</span><span lang="EN-US">738</span><span style="font-family: 仿宋_GB2312;">毫米，并建有库容量</span><span lang="EN-US">2468</span><span style="font-family: 仿宋_GB2312;">万立方米的安口镇大迫子水库；年均日照发电时长约</span><span lang="EN-US">1300</span><span style="font-family: 仿宋_GB2312;">小时，年均风速阈值约每秒</span><span lang="EN-US">5.5</span><span style="font-family: 仿宋_GB2312;">米。同时，我县经济开发区中溢科技公司建设的石墨电极和锂离子电池负极材料项目，年均耗电量约</span><span lang="EN-US">15</span><span style="font-family: 仿宋_GB2312;">亿度，用电需求巨大。结合优越的天然条件和用电消纳情况，我县非常适宜大力发展风力发电、分布式屋顶光伏和抽水蓄能等清洁能源产业。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">（一）光伏发电</span></p>
<p class="112" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312; color: windowtext;">柳河县共有</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">15</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个乡镇、</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">3</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个街道，辖</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">219</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个行政村。全县拥有</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">509</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个自然屯，约有民用变压器</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">820</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个，安全容量约</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">11.034</span><span style="font-family: 仿宋_GB2312; color: windowtext;">万千瓦（</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">110MW</span><span style="font-family: 仿宋_GB2312; color: windowtext;">）。近年来，我县积极推动光伏电站产业发展，先后落地了</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">1</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个集中式和</span><span lang="EN-US" style="font-family: 'Times New Roman', serif; color: windowtext;">1</span><span style="font-family: 仿宋_GB2312; color: windowtext;">个分布式光伏发电项目：</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><strong><span style="font-family: 仿宋_GB2312;">一是柳河县</span></strong><strong><span lang="EN-US">25MW</span></strong><strong><span style="font-family: 仿宋_GB2312;">光伏产业园项目。</span></strong><span style="font-family: 仿宋_GB2312;">项目总投资</span><span lang="EN-US">2.02</span><span style="font-family: 仿宋_GB2312;">亿元，属国家投资的集中式光伏电站项目，是脱贫攻坚期间吉林省唯一由政府主导实施、没有企业参与商业运行的扶贫电站项目。项目分为两期建设，其中：一期</span><span lang="EN-US">10MW</span><span style="font-family: 仿宋_GB2312;">项目主要建设了装机</span><span lang="EN-US">4MW</span><span style="font-family: 仿宋_GB2312;">的</span><span lang="EN-US">38</span><span style="font-family: 仿宋_GB2312;">个村级电站和三源浦周家村</span><span lang="EN-US">6MW</span><span style="font-family: 仿宋_GB2312;">县级电站，电站于</span><span lang="EN-US">2017</span><span style="font-family: 仿宋_GB2312;">年</span><span lang="EN-US">3</span><span style="font-family: 仿宋_GB2312;">月开工建设，同年</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">月</span><span lang="EN-US">29</span><span style="font-family: 仿宋_GB2312;">日并网发电，电价按照</span><span lang="EN-US">0.88</span><span style="font-family: 仿宋_GB2312;">元</span><span lang="EN-US">/</span><span style="font-family: 仿宋_GB2312;">度结算。二期</span><span lang="EN-US">15MW</span><span style="font-family: 仿宋_GB2312;">项目位于三源浦新世村，于</span><span lang="EN-US">2018</span><span style="font-family: 仿宋_GB2312;">年</span><span lang="EN-US">3</span><span style="font-family: 仿宋_GB2312;">月开工建设，同年</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">月</span><span lang="EN-US">28</span><span style="font-family: 仿宋_GB2312;">日并网发电，电价按照</span><span lang="EN-US">0.75</span><span style="font-family: 仿宋_GB2312;">元</span><span lang="EN-US">/</span><span style="font-family: 仿宋_GB2312;">度结算。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><strong><span style="font-family: 仿宋_GB2312;">二是能科源烨分布式屋顶光伏发电项目。</span></strong><span style="font-family: 仿宋_GB2312;">项目计划总投资</span><span lang="EN-US">3.8</span><span style="font-family: 仿宋_GB2312;">亿元，由国有合资企业上海能科源烨能源科技发展有限公司出资建设。项目计划在全县</span><span lang="EN-US">509</span><span style="font-family: 仿宋_GB2312;">个自然屯建设总装机容量</span><span lang="EN-US">100MW</span><span style="font-family: 仿宋_GB2312;">的分布式屋顶光伏项目，项目运营模式为：公司租赁农户屋顶或闲置场地安装分布式光伏发电系统，并按季度向农户进行收益结算。标准为：前</span><span lang="EN-US">10</span><span style="font-family: 仿宋_GB2312;">年每片光伏板每年</span><span lang="EN-US">50</span><span style="font-family: 仿宋_GB2312;">元；后</span><span lang="EN-US">15</span><span style="font-family: 仿宋_GB2312;">年每片光伏板每年</span><span lang="EN-US">40</span><span style="font-family: 仿宋_GB2312;">元。项目售电收益为公司所有，售电价格为</span><span lang="EN-US">0.37</span><span style="font-family: 仿宋_GB2312;">元</span><span lang="EN-US">/</span><span style="font-family: 仿宋_GB2312;">度。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">（二）风力发电</span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span style="font-family: 仿宋_GB2312;">柳河县属北温带大陆性季风气候，四季分明，春季风大干燥，夏季湿润多雨，秋季温和凉爽，冬季漫长寒冷。经谷歌气象卫星大数据库测算分析，柳河县域内风力资源较好的四个区域分别为：凉水镇至孤山子镇区域、三源浦镇至红石镇区域、安口镇至向阳镇区域、亨通镇至圣水镇区域。经生态、环保、军事、文物、林业、自然资源等部门排查筛选后，安口镇至向阳镇、亨通镇至圣水镇两个区域符合风电项目落地条件。近年来，通过金风科技和华润电力测风数据得知，向阳镇和圣水镇年均风速阈值约每秒</span><span lang="EN-US">5.5</span><span style="font-family: 仿宋_GB2312;">米，年均发电时长约</span><span lang="EN-US">2600</span><span style="font-family: 仿宋_GB2312;">小时，可开发的风力资源总量约</span><span lang="EN-US">450</span><span style="font-family: 仿宋_GB2312;">&mdash;</span><span lang="EN-US">500MW</span><span style="font-family: 仿宋_GB2312;">，其中：向阳镇区域约</span><span lang="EN-US">150MW</span><span style="font-family: 仿宋_GB2312;">，圣水镇约</span><span lang="EN-US">300MW</span><span style="font-family: 仿宋_GB2312;">。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span lang="EN-US">2018</span><span style="font-family: 仿宋_GB2312;">年以来，我县先后与中京电投、三峡电力、葛洲坝、金风科技、华润电力、华能电力、中能建等多户大型电力企业进行项目对接并达成合作意向，先后签订清洁能源项目框架合作协议</span><span lang="EN-US">30</span><span style="font-family: 仿宋_GB2312;">余份。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span lang="EN-US">2022</span><span style="font-family: 仿宋_GB2312;">年</span><span lang="EN-US">6</span><span style="font-family: 仿宋_GB2312;">月</span><span lang="EN-US">16</span><span style="font-family: 仿宋_GB2312;">日，我县取得省能源局</span><span lang="EN-US">21.9MW</span><span style="font-family: 仿宋_GB2312;">乡村振兴风力发电指标。省能源局文件中明确，该项目属于公益类项目，由政府或企业全资建设，风电项目纯收益部分捐赠用于支持项目所在县、市乡村振兴发展。目前，该项目取名为：柳河县金风乡村振兴风电示范项目，选址于向阳镇区域，由北京天润新能投资有限公司负责建设运营。项目计划投资约</span><span lang="EN-US">1.37</span><span style="font-family: 仿宋_GB2312;">亿元，主要建设</span><span lang="EN-US">5</span><span style="font-family: 仿宋_GB2312;">台中速永磁风电机组，总装机量</span><span lang="EN-US">21.65MW</span><span style="font-family: 仿宋_GB2312;">。项目计划将于</span><span lang="EN-US">2023</span><span style="font-family: 仿宋_GB2312;">年</span><span lang="EN-US">7</span><span style="font-family: 仿宋_GB2312;">月前完成建设，并网售电价格为</span><span lang="EN-US">0.37</span><span style="font-family: 仿宋_GB2312;">元</span><span lang="EN-US">/</span><span style="font-family: 仿宋_GB2312;">度。该项目为我省东南部首个乡村振兴风电项目。预计项目建成后，将为我省东南部绿电产业发展起到强力的引领作用，为我县后续风电项目建设提供参考。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px; font-family: 黑体;">（三）水利发电</span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><span lang="EN-US">2022</span><span style="font-family: 仿宋_GB2312;">年，柳河县与中国能源建设集团、葛洲坝集团、中建生态环境集团达成抽水蓄能项目合作意向，并签订了项目框架合作协议。经我县与中水东北勘测设计研究院就项目选址进行多次对接，对全县地形进行分析筛选，初步选定两处适合建设抽水蓄能电站的站点。其中：</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0pt; line-height: 29.0pt; mso-line-height-rule: exactly;"><span style="font-size: 18px;"><strong><span style="font-family: 仿宋_GB2312;">&ldquo;柳河安口抽水蓄能电站&rdquo;</span></strong><span style="font-family: 仿宋_GB2312;">选址于安口镇大迫子水库附近，依托已建成的水库为下库，初步设计建设方案可达到装机容量</span><span lang="EN-US">150</span><span style="font-family: 仿宋_GB2312;">万千瓦（</span><span lang="EN-US">1500MW</span><span style="font-family: 仿宋_GB2312;">），水头</span><span lang="EN-US">261.8</span><span style="font-family: 仿宋_GB2312;">米，距高比</span><span lang="EN-US">11</span><span style="font-family: 仿宋_GB2312;">，预计投资约</span><span lang="EN-US">100</span><span style="font-family: 仿宋_GB2312;">亿元。<strong>&ldquo;柳河和平抽水蓄能电站&rdquo;</strong>选址于红石镇和平水库附近，规划装机容量</span><span lang="EN-US">120</span><span style="font-family: 仿宋_GB2312;">万千瓦（</span><span lang="EN-US">1200MW</span><span style="font-family: 仿宋_GB2312;">），水头</span><span lang="EN-US">190</span><span style="font-family: 仿宋_GB2312;">米，距高比</span><span lang="EN-US">13</span><span style="font-family: 仿宋_GB2312;">，预计投资额约</span><span lang="EN-US">70</span><span style="font-family: 仿宋_GB2312;">亿元。</span></span></p>
<p><span style="font-size: 18px; font-family: 仿宋_GB2312;">&nbsp; &nbsp; &nbsp; &nbsp;目前，两座抽水蓄能电站已纳入<a name="_Toc27066"></a><a name="_Toc30153"></a><a name="_Toc25325"></a>《通化市能源发展&ldquo;十四五&rdquo;规划》。柳河安口抽水蓄能电站正在准备向国家申报。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
