//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">旅游休闲产业</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、柳河县旅游资源整体概况</strong></span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县地处吉林省东南部，资源优势和区位优势明显，是一个&ldquo;七山半水二分田，半分道路和庄园&rdquo;的山区县。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">截止目前，全县有<span lang="EN-US">4A</span>级景区<span lang="EN-US">1</span>家、<span lang="EN-US">3A</span>级景区<span lang="EN-US">4</span>家、<span lang="EN-US">3A</span>级旅游经营单位<span lang="EN-US">4</span>家，省级自然保护区<span lang="EN-US">1</span>处、国家级森林公园<span lang="EN-US">1</span>家、全国重点文物保护单位<span lang="EN-US">2</span>处、正待开发景区<span lang="EN-US">4</span>处、旅行社及门市部<span lang="EN-US">5</span>家、星级宾馆<span lang="EN-US">2</span>家。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、柳河县旅游产业发展情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">一是强化组织保障。成立全域旅游创建工作领导小组，把创建工作纳入绩效考核。注册柳河县畅客文化旅游投资责任公司和柳河印像国际旅行社，设立<span lang="EN-US">1000</span>万元旅游发展引导资金，研究制定《柳河县加快旅游业发展的若干意见》，进一步加强了组织领导和工作保障。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">二是谋划储备项目。累计谋划&ldquo;十四五&rdquo;旅游项目<span lang="EN-US">12</span>个，总投资<span lang="EN-US">140</span>亿元。其中，通化&middot;<span lang="EN-US">MVR</span>世博村一体化试验区项目纳入省&ldquo;十四五&rdquo;整体规划。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">三是坚持规划先行。柳河先后完成青龍山滑雪场、别有洞天、衍庶街、红色历史文化馆、田园枫谷、相思谷等<span lang="EN-US">8</span>个景区详细规划编制，作为&ldquo;十四五&rdquo;期间产业重点发展方向，形成了核心突出、覆盖全域、点线带相结合的全域旅游发展格局。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、景区介绍</strong></span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）罗通山风景旅游区简介</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">罗通山风景旅游区位于吉林省柳河县东北部，距县城<span lang="EN-US">35</span>公里，景区总面积<span lang="EN-US">6267</span>公顷，山巅面积<span lang="EN-US">3133</span>公顷，最高海拔<span lang="EN-US">1090</span>米。景区核心区域为罗通山城，是全国重点文物保护单位，是全国乃至亚洲第二大高句丽山城，是高句丽&ldquo;左右式&rdquo;山城的典型代表。城内尚存城墙、城门遗址、角楼遗址、点将台遗址、蓄水池遗址、演兵场，兵营遗址等多处遗址，出土文物较多。罗通山风景旅游区汇集以高丽古城为代表的历史人文景观，以背阴洞、穿心洞、水帘洞、通天洞等溶洞群为代表的地质景观，以特有古石榆、野生动植物资源为代表的生态景观，以道观三清宫为代表的宗教旅游景观，四大景观资源，融为一体，独具特色；更有城古，洞幽，塞要、崖险、林密、花绚等六大自然看点。罗通山城的综合资源优势在吉林省乃至东北地区旅游景观中，堪称上乘。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）云岭野山参风景旅游区简介</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">云岭野山参风景旅游区坐落在吉林省柳河县向阳镇，地处长白山区云岭山脉。景区占地面积<span lang="EN-US">16000</span>亩，其内部设施齐全，景观独特，有特色民宿、造型各异的森林别墅群、地下酒窖、人参博物馆、多功能会议厅、射击场、滑雪场、植物迷魂阵、垂钓园、采摘园等设施。云岭先后被评为国家<span lang="EN-US">3A</span>级旅游景区和吉林野山参原料基地，景区研发生产的野山参粉、野山参片、野山参汁，作为中国野山参第一品牌，已经获得国家首个批准文号，产品享誉内外。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）三仙夹国家森林公园简介</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">三仙夹国家森林公园始建于<span lang="EN-US">1992</span>年，距柳河县城东南<span lang="EN-US">10</span>公里，因地处三人班、仙人沟、夹皮沟交界处而得名。<span lang="EN-US">1993</span>年经原国家林业部正式批准为国家级森林公园，森林公园现总面积为<span lang="EN-US">13200</span>亩，森林覆盖率<span lang="EN-US">95%</span>，拥有景点<span lang="EN-US">33</span>处，是集野生动植物保护区与旅游开发区为一体的国家级森林公园。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（四）&ldquo;别有洞天&rdquo;红色旅游景区</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">项目位于五道沟镇大泉眼村水泥厂旧址，总占地面积约<span lang="EN-US">1072</span>亩。项目以人工采石洞、天然溶洞为主体，以地域红色文化为主体，充分利用当地抗联、四保临江等红色历史史实，打造集洞穴探险、红色教育、工业体验为一体的综合旅游景区。主要建设洞内景观、历史博物馆、山洞服务中心、仿古城墙、仿古城楼等设施。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（五）衍庶街</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">衍庶街文化旅游开发项目位于柳河西南角，西起西绕城路、东至军民路，北至振兴大街，南临木王路。项目总占地面积<span lang="EN-US">26.8</span>万平方米，建筑面积<span lang="EN-US">4.8</span>万平方米，主要建设内容包括：人工湖、湿地水系、绿地花海、体育场、儿童乐园及徽派特色商业街等。</span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（六）珩阳逸景康养小镇<span lang="EN-US">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
<p class="MsoNormal" style="text-indent: 21pt; line-height: 150%; text-align: justify;"><span style="font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">项目位于柳河县罗通山镇东部区域，项目占地面积<span lang="EN-US">1400</span>亩，建筑面积<span lang="EN-US">5.13</span>万平方米。项目以康养小镇建设为核心，主要建设内容包含：漂流体验、冰雪运动、休闲娱乐、集旅居养老、观光农业、清洁能源、有机农产品生产等于一身的综合性旅游开发项目。<span lang="EN-US">&nbsp; &nbsp; &nbsp;</span></span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
