//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">安口镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">安口镇位于柳河县城西南部<span lang="EN-US">19</span>公里处，辖<span lang="EN-US">17</span>个行政村，<span lang="EN-US">38</span>个自然屯，人口总数<span lang="EN-US">7111</span>户、<span lang="EN-US">21434</span>人。全镇幅员面积<span lang="EN-US">258</span>平方公里，其中旱田<span lang="EN-US">6.8</span>万亩，水田<span lang="EN-US">1.2</span>万亩，果园<span lang="EN-US">0.2</span>万亩、大榛子<span lang="EN-US">2.84</span>万亩，林地<span lang="EN-US">38.4</span>万亩，经济产值<span lang="EN-US">6</span>亿元。镇区域糸龙岗山支脉，海拔<span lang="EN-US">370-1255</span>米之间，由一统河贯穿南北，河堤两岸较为平坦、土质肥沃，自然资源丰富，生态环境优美，近年来先后获得国家级<span lang="EN-US">&ldquo;</span>农业产业强镇<span lang="EN-US">&rdquo;&ldquo;</span>一村一品示范村镇<span lang="EN-US">&rdquo;</span>，省级<span lang="EN-US">&ldquo;</span>吉林柳河安口榛臻特色产业示范镇<span lang="EN-US">&rdquo;&ldquo;</span>特产之乡<span lang="EN-US">&rdquo;</span>等国家级荣誉<span lang="EN-US">7</span>项、省级荣誉<span lang="EN-US">9</span>项。<span lang="EN-US">2018</span>年<span lang="EN-US">8</span>月全省乡村振兴现场会在安口镇召开，省委书记景俊海带领省市领导<span lang="EN-US">600</span>余人进行参观指导，得到省市领导一致好评。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">自然情况：</span></strong></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">安口镇东邻柳河县，西接向阳镇，南接三源浦镇，北靠梅河口市吉乐乡，柳新线省级公路纵贯全境，交通非常便利。自然资源比较丰富，主要以天然林为主，大小生态沟近百条。镇内水利资源较为丰富，柳河水库为县城柳河县城主要饮用水源地，安口水库为柳河县城备用水源地，水库运行情况良好。安口镇积极建设和谐宜居的美丽安口，半拉背村被评为国家级生态村，烧锅村被评为省级美丽乡村。大沙滩、半拉背村被列入省级生态村序列。镇内建有电子商务中心、青年农民学校、农民夜校、文化大院等相关附属配套设施齐全。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>产业发展现状：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">安口镇以<span lang="EN-US">&ldquo;</span>生态、产业、旅游<span lang="EN-US">&rdquo;</span>协调发展为目标，加快推进幸福美丽新安口建设，为乡村振兴奠定良好基础。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">榛子产业：安口镇林地资源比较丰富、地理环境优越，大榛子生长条件适宜，可利用现有林地资源优势，开展多种经营，发展特色特色大榛子产业是促进农林业发展的有效途径，利用停耕还林土地，合理开发利用，栽植与培育大果榛子经济林，实现传统农业向休闲农业转型，推动乡村振兴步伐。安口镇现有榛子种植面积<span lang="EN-US">2.84</span>万亩（产果期面积<span lang="EN-US">1.7</span>万亩）。现有<span lang="EN-US">200</span>亩以上种植基地<span lang="EN-US">31</span>个，有种植农户<span lang="EN-US">602</span>户，<span lang="EN-US">2016</span>年<span lang="EN-US">12</span>月被国家九部委评选为&ldquo;国家级农民合作社示范社&rdquo;。<span lang="EN-US">2017</span>年建设占地<span lang="EN-US">70</span>亩<span lang="EN-US">33</span>栋现代高科技扦插育苗大棚基地、<span lang="EN-US">50</span>万吨榛子仓储中心与深加工生产线。<span lang="EN-US">2017</span>年成功组建柳河县大果榛子产业商会，入会会员达<span lang="EN-US">56</span>名，商会拥有线上商铺<span lang="EN-US">12</span>家，大榛子种植合作社<span lang="EN-US">31</span>家，仅商会现有种植榛子面积达<span lang="EN-US">1.7</span>万亩。<span lang="EN-US">2017</span>年获得&ldquo;全国一村一品示范村镇、国家级电商镇、国家级保障基本村、国家级社区、国家级农民合作社示范社、省级电商小镇、吉林省特产之乡&rdquo;荣誉称号；<span lang="EN-US">2018</span>年获得&ldquo;全国生态文化村、吉林省林业产业基地、吉林省&ldquo;一村一品&rdquo;示范村&rdquo;荣誉称号；<span lang="EN-US">2019</span>年获得&ldquo;国家级农业产业强镇、省级柳河安口榛臻特色产业示范镇、吉林省精神文明建设先进集体（安口镇）、吉林省精神文明建设先进集体（烧锅村）&rdquo;荣誉称号、<span lang="EN-US">2020</span>年获得第二批全国乡村旅游重点村荣誉称号（青沟子村）。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">榛子产业<span lang="EN-US">2019</span>年成功申报国家级农业产业强镇，获得国家奖补资金<span lang="EN-US">1000</span>万元，撬动社会投资<span lang="EN-US">4200</span>万元，成功申报吉林省榛臻特色小镇，获得省扶持资金<span lang="EN-US">600</span>万元。柳河县园丰大榛子专业合作社是经中央九部委颁发的<span lang="EN-US">&ldquo;</span>国家级合作社示范社<span lang="EN-US">&rdquo;</span>。先后发起组建大榛子产业商会，吉林省榛子产业联合社，安口镇上下联动，建立健全联动带农机制，实现了多方共赢。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">苗木产业：安口镇现有苗木种植面积<span lang="EN-US">9000</span>余亩，苗木产业，由上世纪<span lang="EN-US">80</span>年代开始，镇域北部村屯开始种植培育荒山造林苗木，经过历年来的发展，苗木产业先后获得国家级<span lang="EN-US">&ldquo;</span>中国北方苗木基地<span lang="EN-US">&rdquo;</span>、中国北方苗木交易市场等荣誉。苗木远销东北、西北、新疆等十多个省份，为国家还林、荒山绿化提供了强有力的保障。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游产业：积极发展冰雪经济，稳步推进中国通化<span lang="EN-US">MVR</span>世博村一体化试验区项目建设，安口镇青沟子村<span lang="EN-US">2020</span>年成功举办柳河首届冰雪旅游节开幕式，青龍山滑雪场初级雪道现已接待运营，青沟子村以此荣获全国第二批旅游重点村。结合<span lang="EN-US">&ldquo;</span>榛臻小镇<span lang="EN-US">&rdquo;</span>、十二坊农家乐和安口水库休闲游项目，形成风格独特、景观优美、一区一文化、一处一亮点的安口镇旅游特色。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>未来发展方向及合作意向：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">立足于我镇的资源优势，结合现有产业基础和市场前景，竭诚期望社会各界人士积极参与进来，更加热切的欢迎广大朋友来安口观光旅游、投资兴业、合作共赢。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
