//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">采胜街道</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">采胜街道成立于2019年4月，总面积27.26平方公里，位于柳河县城东部，紧邻县工业园区，含城市和乡村两大区块，具有城乡融合发展的区位优势，集锡高速、通梅路、县道、铁路等交通网，纵横交错、四通八达。现辖3个城市社区、4个行政村、5个自然屯，总人口15944户38943人</span><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">。</span><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">辖区共有生产经营业户1503家，规模企业8家。耕地面积7458亩，其中：水田面积960亩、旱田面积6518亩）、果园320亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">1.水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">采胜街道水利资源十分充沛，水利设施完善。境内主要有一统河、哈尼河、柳树河、小堤河等4段河流，有小二型水库1座（柞木村水库总库容量31.68万立方米，库区周长2公里，库内生长10多个淡水鱼种，年产淡水鱼2万斤，灌溉面积3800亩），大小塘坝10个，拦河坝1座，电灌站1座。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">2.林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">森林面积16650亩（补植补造113亩），系长白山林区组成部分，由天然<a href="https://baike.baidu.com/item/%E9%92%88%E9%98%94%E6%B7%B7%E4%BA%A4%E6%9E%97"><span style="mso-ascii-font-family: 宋体; mso-fareast-font-family: 宋体; mso-hansi-font-family: 宋体;">针阔混交林</span></a>、次生阔叶林和人工林构成，山野菜、食用菌等林下物产丰富。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">3.人力资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">劳动人口10926人，其中城区9895人、乡村1031人，占总人口的28%。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">4.旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">采胜街道主要结合山水资源以城郊山庄旅游为主，区域内现有柞木村瓜果种植采摘园、柞木村水库休闲山庄、钓鱼台村晟源休闲山庄、采胜村馨林湾生态源山庄等，为城区及短途居民度假旅游、休闲养生提供了方便。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">1.休闲旅游产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;">采胜街道现有3家休闲旅游山庄、1家种植采摘园。一是钓鱼台村晟源休闲山庄，投资约500万元，2007年建设完成，建筑面积730平方米(含养殖场220平方米)，占地面积3400平方米，主要经营项目包括养殖(大约200多头生猪)、餐饮、采摘(苹果园、梨园、杏园)、垂钓、特色烤全羊等，每年接待游客3000余人；二是柞木村水库休闲山庄，投资300余万元，2020年建设完成，建筑面积500平方米，占地面积100亩，主要经营项目包括养殖、餐饮、垂钓、烧烤等，每年接待游客5000余人；三是采胜村馨林湾生态源山庄，投资400余万元，2003年建设完成，建筑面积2000平方米，占地面积700亩，主要经营项目包括养殖、餐饮、采摘、垂钓(能一次容纳200人同时娱乐)、烧烤(全羊、自助烧烤)等，每年接待游客4000余人；四是柞木村瓜果种植采摘园，坐落于柞木岗村，2014年建设完成，占地320亩，主要种植户有86户，其中李子30亩、沙果30亩、葡萄260亩，每年接待游客2000余人。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">酒业产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">采胜街道现有葡萄酒生产销售企业<span lang="EN-US">5</span>家、白酒企业生产销售<span lang="EN-US">1</span>家，分别是源之王葡萄酒有限公司、雪瑞斯葡萄酒有限公司、华龙葡萄酒有限公司、天池山葡萄酒有限公司、钓鱼台酿酒有限公司，生产的葡萄酒、白酒系列产品在国内（国外）市场都有一定销售。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">养殖种植产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">采胜街道现有养殖合作社<span lang="EN-US">2</span>个，<span lang="EN-US">15</span>个养牛专业户、<span lang="EN-US">1</span>个集中养殖场、<span lang="EN-US">320</span>头牛（<span lang="EN-US">20</span>头奶牛）、年繁殖小牛（<span lang="EN-US">100</span>头），葡萄种植合作社<span lang="EN-US">1</span>个，<span lang="EN-US">86</span>个种植专业户、种植面积<span lang="EN-US">320</span>亩，米业合作社<span lang="EN-US">1</span>个，<span lang="EN-US">36</span>个专业户，养殖、种殖产业初具规模。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt; mso-fareast-language: EN-US;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 10.0pt; line-height: 150%; font-family: 宋体; mso-font-kerning: 0pt;">以&ldquo;绿水青山就是金山银山，冰天雪地也是金山银山&rdquo;为理念，以建设基础设施、城市生活配套服务、山庄休闲旅游、洒业加工销售、养殖种植等为牵引，依托紧邻县工业园区和发达的交通网络地理优势为抓手，不断优化整合资源，以带动区域产业发展，拉动群众创收，提升人民生活品味为目标，打造新的&ldquo;园区<span lang="EN-US">+</span>地域&rdquo;特色旅游产业圈。</span></p>
<p>&nbsp;</p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
