//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">孤山子镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">孤山子镇地处<span lang="EN-US"><a href="https://baike.so.com/doc/5726473-5939211.html"><span lang="EN-US"><span lang="EN-US">柳河县</span></span></a></span>东南部，是一个有着百余年历史和较强辐射能力的商贸型中心集镇。全镇行政区面积<span lang="EN-US">280.3</span>平方公里，辖<span lang="EN-US">24</span>个行政村，<span lang="EN-US">68</span>个自然屯，总人口<span lang="EN-US">2.9</span>万人。南部与通化县兴林镇接壤，东、北、西部分别与凉水、姜家店、驼腰岭、五道沟、三源浦等乡镇搭界，是<span lang="EN-US"><a href="https://baike.so.com/doc/5726473-5939211.html"><span lang="EN-US"><span lang="EN-US">柳河县</span></span></a></span>东南部乡镇的经济交流、文化教育、医疗卫生、工商业服务中心和农副产品的主要集散地。全镇耕地面积<span lang="EN-US">8191</span>公顷，其中水田面积<span lang="EN-US">1996</span>公顷；集体林地面积<span lang="EN-US">5120</span>公顷，<span lang="EN-US">2020</span>年全口径财政收入<span lang="EN-US">830</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">镇内流经哈泥河和三统河两条大河，两条河流汇集大小支流<span lang="EN-US">60</span>余条，其中<span lang="EN-US">10</span>公里以上的支流有<span lang="EN-US">3</span>条，<span lang="EN-US">5</span>公里以上的有<span lang="EN-US">8</span>条。同时，有水库塘坝<span lang="EN-US">41</span>座和电灌站<span lang="EN-US">9</span>处，灌溉镇域十万余亩农田。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">镇域南部为山区，北部为半山区，属龙岗山余脉。国营八里哨林场、全胜林场的全部施业区和大北岔林场的大部分施业区都座落在本镇境内，森林面积<span lang="EN-US">129.3</span>平方公里，活立木储量达<span lang="EN-US">58768</span>万立方米，森林覆盖率<span lang="EN-US">46.1%</span>，为野山菜、中草药、食用菌等野生植物的采集、种植和加工以及林蛙等珍奇动物的养殖提供了广阔的场所。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">3.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">域内地下矿物质储量丰富，主要有铁矿石、花岗石、石灰岩、大理石、硅石、钾长石、泥炭、粘土。其中，铁矿分布于龙岗山脉两侧二人班、唐太岭、隆兴、闹枝沟，现已建<span lang="EN-US">4</span>处铁矿开发生产。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">4.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">镇内有大河屯东北抗联遗迹红色教育建筑示范群落<span lang="EN-US">1</span>处，建有地窨子、窝棚、瞭望哨、木质住宅，并修复了抗联临时医院、修械所、粮豆窝子、头道河子会议遗址。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">矿产开发业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">孤山子镇工业企业以铁矿企业为主，<span lang="EN-US">2021</span>年有<span lang="EN-US">4</span>家铁矿企业在生产或建设中。一是柳河县七棵树矿业有限公司投资<span lang="EN-US">5000</span>万元，在孤山子镇隆兴村新建选矿厂，占地<span lang="EN-US">35</span>亩，购置新设备<span lang="EN-US">40</span>台（套），建设新厂房<span lang="EN-US">2000</span>平方米。已探明铁精粉储量<span lang="EN-US">200</span>万吨，项目建成后预计年生产<span lang="EN-US">50</span>万吨铁精粉。二是柳河县隆盛坤矿业有限公司<span lang="EN-US"><span style="mso-tab-count: 1;"> </span></span>投资<span lang="EN-US">1000</span>万元，在板庙子采矿点建设选矿设施，购入设备<span lang="EN-US">35</span>台（套），已探明铁精粉储量<span lang="EN-US">150</span>万吨，项目建成后预计年生产铁精粉<span lang="EN-US">6.6</span>万吨。三是通化好运来矿业有限公司投资<span lang="EN-US">7000</span>万元，<span lang="EN-US">2021</span>年进行井下工程及尾矿库改造，已探明铁精粉储量<span lang="EN-US">70</span>万吨，预计年产铁精粉<span lang="EN-US">6</span>万吨。四是柳河县金田选矿有限公司铁精粉生产项目投资<span lang="EN-US">500</span>万元，<span lang="EN-US">2021</span>年对原有老旧选矿设备全部拆除，更新选矿用设备<span lang="EN-US">10</span>台（套），对厂区进行全面修缮，恢复生产，预计年生产铁精粉<span lang="EN-US">6</span>万吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">规模农业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">孤山子镇农业产业以<span lang="EN-US">&ldquo;</span>一核两驱多轸<span lang="EN-US">&rdquo;</span>产业体系助推经济社会发展。<span lang="EN-US">&ldquo;</span>一核<span lang="EN-US">&rdquo;</span>即高台村十里香农机专业合作社、润泽苗木专业合作社，年经营性收入可达<span lang="EN-US">200</span>万元；<span lang="EN-US">&ldquo;</span>两驱<span lang="EN-US">&rdquo;</span>为南围子村<span lang="EN-US">500</span>头黄牛标准化养殖基地及西街村<span lang="EN-US">14000</span>平米蔬菜大棚，经营性收入各为<span lang="EN-US">25</span>万元、<span lang="EN-US">46.2</span>万元。<span lang="EN-US">&ldquo;</span>多轸<span lang="EN-US">&rdquo;</span>指积极发展葡萄、蓝莓、食用菌、中药材等特色农业，全面拓展销售渠道、拓宽乡村产业增值空间，推动乡村特色产业可持续发展。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;"><strong>四、未来发展方向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">孤山子镇根据农村自然禀赋、资源条件和区位特点，坚持规划先行，围绕打造孤山子镇&ldquo;百年商贸古镇&rdquo;品牌，秉持自然美、侧重现代美、注重个性美、构建整体美的原则，还原乡村风貌、乡村环境、乡村特色，科学设计美丽乡村发展规划，积极打造可体现<span lang="EN-US">&ldquo;<a href="http://m.baidu.com/s?word=%E4%B8%80%E6%9D%91%E4%B8%80%E5%93%81&amp;from=1011904q&amp;fenlei=mv6quAkxIv-1ufKYIHdsIHDsnj0Yr0K15Hnvn10YPyc3PjnduhmdnWf0mv4YUWYknj0sPj9xuZPs0ZNzUjdCIZwsrBtEXM9BQM-GuZR8uvqvQhP8Qv7zIatznjDdQ1mEnHcEmgFYg1cvPWbsg1TkrH6YPi4CIAd_" target="https://m.baidu.com/from=844b/bd_page_type=1/ssid=0/uid=0/pu=sz%401320_2001%2Cta%40iphone_1_10.1_3_602%2Cusm%400/baiduid=C98C2200974B7148ECF331EAFEE92E63/w=0_10_/t=iphone/l=3/_blank"><span lang="EN-US"><span lang="EN-US">一村一</span></span></a></span>品、一村一韵<span lang="EN-US">&rdquo;</span>的百年古镇人文特色的民宿精品；大力发展文旅商贸产业，重点打造以<span lang="EN-US">&ldquo;</span>三回线<span lang="EN-US">&middot;</span>哈泥河<span lang="EN-US">&rdquo;</span>风光游、参谷雪乡冰雪游、大河屯抗联遗迹红色文化游的载体，构建集<span lang="EN-US">&ldquo;</span>吃住娱购游<span lang="EN-US">&rdquo;</span>一体的文化服务旅游产业格局，欢迎四方来客前来共建共襄。</span></p>
<p>&nbsp;</p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
