//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">亨通镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">亨通镇地处吉林省东南部长白山区，位于柳河县东部，距县城<span lang="EN-US">22.5</span>公里，幅员面积<span lang="EN-US">107</span>平方公里，辖<span lang="EN-US">7</span>个行政村，<span lang="EN-US">23</span>个自然屯，总户数为<span lang="EN-US">13254</span>户，总人口<span lang="EN-US">13340</span>人，劳动力<span lang="EN-US">7068</span>人，占总人口<span lang="EN-US">54.78%</span>。耕地总面积<span lang="EN-US">46285</span>亩；果园总面积<span lang="EN-US">1007.25</span>亩；全镇<span lang="EN-US">23</span>个自然屯实现水泥路&ldquo;村村通&rdquo;。平均日照时数为<span lang="EN-US">7</span>小时，年均降水量<span lang="EN-US">760</span>毫米、无霜期达到<span lang="EN-US">140</span>天。山、水、田、林交相辉映，青山碧水、四时俱胜。钟灵毓秀、物华天宝，开放包容的黑土地展示着亨通镇的魅力多姿；海纳百川、厚德载物，不断优化升级的产业奏响亨通镇腾飞奋进的激扬旋律。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">镇内流经窝集河和李大院沟河以及南淤泥河三条大河，水库塘坝<span lang="EN-US">202</span>座，其中：小Ⅰ型水库<span lang="EN-US">1</span>座，小Ⅱ型水库<span lang="EN-US">11</span>座，集体塘坝<span lang="EN-US">60</span>座，个人塘坝<span lang="EN-US">130</span>座，电灌站<span lang="EN-US">8</span>座，拦河闸；灌溉镇域七万余亩农田。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">镇域南部为半山区，北部为丘陵，属罗通山余脉。森林面积<span lang="EN-US">8.16</span>万亩，森林覆盖率<span lang="EN-US">21%</span>，亨通镇是商品粮食基地，生产大量优质油质玉米，外销大连、营口等地现有成果<span lang="EN-US">3000</span>余亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">域内地下矿物质储量丰富，有铁、铅、铝、煤、白土、石灰石、硅、稀土等，其中亨通村煤储量<span lang="EN-US">2</span>万吨；太平沟村山中硅石和石膏石，储量分别为<span lang="EN-US">476</span>万吨、<span lang="EN-US">1</span>亿吨；黑崴子村马家街有铁、铅、石灰石、硅、稀土等矿藏，于大房子村南淤泥屯地下有高岭稀土矿藏；南淤泥河子有较丰富的白土矿，马家街屯东南部有石灰石、铁、铝等矿藏；</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">镇内有蔡家屯二十四节气中药养生馆<span lang="EN-US">1</span>处，室内分为一层党建联盟基地、可品尝中药养生茶，二层展示我镇中草药实物、药用价值，作用等介绍，室外并建有日冕可供观赏，停车场可供停放车辆。观光采摘大棚<span lang="EN-US">13</span>栋；果树采摘园<span lang="EN-US">300</span>亩；农家乐民宿山庄<span lang="EN-US">3</span>个。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色棚膜果蔬产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">亨通镇现有大棚<span lang="EN-US">13</span>栋，主要发展蔬菜和水果种植产业。近年来镇政府不断加大政策扶持力度，培育出一批优秀专业种植合作社。其中，以蔡家屯成涛种植专业合作社为主要代表，发展果树采摘园<span lang="EN-US">300</span>亩，油桃采摘大棚<span lang="EN-US">6</span>栋。<span lang="EN-US">2021</span>年建设占地面积<span lang="EN-US">55.5</span>亩的果蔬温室<span lang="EN-US">7</span>栋，用于栽种<span lang="EN-US">99</span>草莓、蔬菜等。<span lang="EN-US"><br />2.</span>特色中草药材产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">亨通镇中草药材种植面积达<span lang="EN-US">3000</span>余亩，集中分布在姜家村和黄崴子村，主要种植北苍术、黄精、射干、五味子等道地药材共计<span lang="EN-US">25</span>个品种。<span lang="EN-US">2020</span>年<span lang="EN-US">6</span>月在黄崴子村挂牌成立北苍术规范化种植实验基地和北苍术技术工作站，实现对基地、种植大户的生产指导全覆盖。通过长春中医药大学党建联盟示范引领、技术支撑，积极引导各村建设中药种植示范区，探索形成区域产业。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">畜牧养殖</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">亨通镇家畜家禽存栏量<span lang="EN-US">60</span>余万头（只），其中，猪<span lang="EN-US">1240</span>头、牛<span lang="EN-US">723</span>头、羊<span lang="EN-US">302</span>只、鸡<span lang="EN-US">60</span>万只。养殖大户有<span lang="EN-US">38</span>户，其中养鸡户<span lang="EN-US">30</span>户，养猪<span lang="EN-US">7</span>户，养牛<span lang="EN-US">1</span>户。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">亨通镇将围绕&ldquo;吃、住、行、旅、购、娱&rdquo;旅游六要素打造&ldquo;醉美亨通、四香小镇&rdquo;。围绕&ldquo;吃&rdquo;，参观二十四节气中药养生馆品尝养生套餐，黄崴子水库特色冷水鱼小老鱼，有机绿色食品山野菜、山蘑菇和甜食玉米、本地土鸡、大鹅、黑猪肉等农家饭菜；围绕&ldquo;住&rdquo;，蔡家屯特色民宿，可以体验&ldquo;民宿游居&rdquo;；围绕&ldquo;行&rdquo;，在沿线道路游览花海美景；围绕&ldquo;游&rdquo;，春天在苹果园、葡萄园感受果花的香气，夏天在旅游沿线欣赏射干、北苍术、鸡冠花、步步高等多种药材花卉，增加中药材知识，秋天在稻田里体会稻花的香气，冬天在油桃、蔬菜大棚品尝水果、有机蔬菜的甘甜、清香。围绕&ldquo;购&rdquo;，依托线上（电商服务中心）线下（设立特色商品销售点）销售我镇特色中药材（北苍术、黄精、射干、五味子、细辛等）、鸡心果、龙丰果、有机提子、甜食玉米、草编制品、无公害稻米、杂粮、油桃、山野菜、山蘑菇、黑猪肉等，做大做强水果、山珍、小杂粮、药食同源，本地小跑等地方特色产品；将&ldquo;娱&rdquo;贯穿所有要素中，漫步、观赏、垂钓、采摘等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">&ldquo;生态康养地，药香飘万里&rdquo;。钟灵毓秀、魅力多姿的亨通镇诚邀五湖四海宾朋前来观光旅游、投资兴业、共谋发展！</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
