//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">红石镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">红石镇地处东经<span lang="EN-US">125</span>&deg;<span lang="EN-US">45</span>&prime;，北纬<span lang="EN-US">41</span>&deg;<span lang="EN-US">59</span>&prime;。位于柳河县西南部，南部与通化县四棚乡接壤，东西相距<span lang="EN-US">19</span>公里，东北到西南最长，约<span lang="EN-US">24</span>公里，位于柳河县西南部，属于半山区，地处北龙岗山脉南麓，南、西、北三面环山，东部多低山。幅员面积<span lang="EN-US">142.79</span>平方公里，辖<span lang="EN-US">7</span>个村，<span lang="EN-US">16</span>个自然屯，户籍总户数<span lang="EN-US">4141</span>户，总人口<span lang="EN-US">11971</span>人。耕地面积<span lang="EN-US">31774</span>亩，其中水田<span lang="EN-US">8110</span>亩，旱田<span lang="EN-US">23664</span>亩。林地面积<span lang="EN-US">8400.3</span>公顷，森林覆盖率<span lang="EN-US">43.2%</span>。镇域内有三统河源头红石河，发源于红石镇青岭村，河长<span lang="EN-US">19.9</span>公里，流域面积<span lang="EN-US">110.4</span>平方公里，河道坡度<span lang="EN-US">3.78</span>&permil;，其支流瓮圈河于红石镇红石村村南汇入红石河，其两岸为河谷平原，土地肥沃。镇域公路总里程<span lang="EN-US">47.62</span>公里，由三红线、由通线、四兰线、进四线、四锡线组成，主要客运线路有三条，西安至柳河快客（红石快客）每天通车<span lang="EN-US">20</span>趟，红石至通化班车一次，兰山至通化班车一次（往返通过本境），连接市区和县城，方便快捷。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">水力资源：水资源总量为<span lang="EN-US">6460</span>万立方米，有大小水库塘坝<span lang="EN-US">8</span>座，其中，和平水库库容<span lang="EN-US">2230</span>万立方米。镇域红石河为三统河源头，全长<span lang="EN-US">19.9</span>公里。和平水库以下，红石河两岸，延镇界分水岭，属于河谷平原，土质肥沃，是柳河县绿优米的主要基地。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">矿产资源：红石镇矿产资源是主要是煤，储藏于四清村的柳条沟。含煤<span lang="EN-US">4</span>层群<span lang="EN-US">17</span>分层。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">森林资源：红石镇属于半山区，地处龙岗山脉，是柳河县国家重点公益林区。境内有林地<span lang="EN-US">13937</span>公顷（国有林区<span lang="EN-US">355</span>公顷），森林资源较为丰富。主要树种有：杨树、榆树、胡桃秋、水曲柳、花曲柳、色树、黄玻罗、柳树、青秸子、椴树、红松、杉松、黑松、白松、落叶松等树种。常用药材人参、细辛、天麻等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">旅游资源：红石镇的和平水库距红石镇政府所在地<span lang="EN-US">3</span>公里，是旅游的好景点，夏天可以乘坐游艇进行游玩，也垂钓的好去处，是人们休闲娱乐的好地方。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">红石镇现有产业与资源情况，主要发展草莓、菜葫芦、烤烟等特色产业，通过建基地、扩规模，推动特色产业发展，为镇域经济发展注入新的活力。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">一是草莓产业。目前总投资<span lang="EN-US">2000</span>余万元建设了<span lang="EN-US">43</span>栋现代化日光温室草莓大棚，由柳河红石康乐现代农业科技有限公司承包。现总占地面积<span lang="EN-US">219</span>亩。园区实施无害、绿色、有机、智能生产，草莓产品已通过<span lang="EN-US">70</span>项的安全检测。仅<span lang="EN-US">2019</span>年总产值可达<span lang="EN-US">1000</span>万元，带动周边劳动力就业<span lang="EN-US">20</span>人（其中贫困户劳动力<span lang="EN-US">10</span>人），人均年增收<span lang="EN-US">1</span>万余元，村级扶贫草莓产业项目共收益<span lang="EN-US">8</span>万元，带动<span lang="EN-US">104</span>户<span lang="EN-US">265</span>人受益。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">二是菜葫芦产业。<span lang="EN-US">2020</span>年全镇共种植菜葫芦<span lang="EN-US">2230</span>亩，可产干条<span lang="EN-US">90.2</span>万斤，总产值可达<span lang="EN-US">108.2</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">三是烤烟产业。<span lang="EN-US">2020</span>年全镇烟田共计<span lang="EN-US">2516</span>亩，其中烟田园区<span lang="EN-US">1160</span>亩。<span lang="EN-US">2019</span>年全镇烟叶总产值<span lang="EN-US">973</span>万元，其中园区烟叶总产值<span lang="EN-US">480</span>万元，返还税收<span lang="EN-US">214</span>万元，园区每年可带动贫困人口务工<span lang="EN-US">60</span>余人，人均年增收约<span lang="EN-US">6000</span>余元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">四是其他产业。葡萄产业：以青岭村、碱厂屯、李油坊村为主，全镇共种植葡萄<span lang="EN-US">508</span>亩，主要有左优红、<span lang="EN-US">28</span>号、双红、北冰红等品种，年产量<span lang="EN-US">381.5</span>吨，总收入可达到<span lang="EN-US">152.6</span>万元。苹果产业：以良种场屯、柳条屯、李油坊村为主，全镇共种植苹果<span lang="EN-US">6540.9</span>亩，主要有玫瑰红、玫瑰香及寒富等品种，年产量可达到<span lang="EN-US">511</span>吨，总收入可达到<span lang="EN-US">255.5</span>万元。人参产业：以西安村、红石村、良种场村为主，发展面积为<span lang="EN-US">2415</span>亩，其中流转土地<span lang="EN-US">1658</span>亩。蓝莓产业：以郭家沟屯、柳条屯为主，全镇共种植蓝莓<span lang="EN-US">450</span>亩，年产量约<span lang="EN-US">55</span>吨，总收入可达到<span lang="EN-US">176</span>万余元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">（一）以工业项目建设为中心，提升发展新实力。吸引优秀者返乡创业<span lang="EN-US">,</span>加快发展烟叶、葡萄、菜葫芦、水稻等特色优势产业深加工；着力发展葡萄酒、白酒、优质米加工等生态环保企业；加快红石镇现代产业园建设，打造具有村级集体经济示范带动作用的小微产业园。集生产、加工、网络营销、农家乐为一体，以规范化管理和规模化种植的形式，全面提高种植效益，集中优势资源和技术力量，进行市场化经营，壮大集体经济，增加农民收入。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">（二）以优化农业结构为重点，打造发展新平台。一方面要调整农业生产布局，突出特色，扩大规模，形成品牌，大力推进农业产业化经营，促进传统农业的优化升级，提高农业的整体效益。积极探索&ldquo;公司＋农户&rdquo;、&ldquo;公司＋合作社＋农户&rdquo;和订单生产等农业产业化经营模式，提高生产组织化程度。另一方面大力培育现代农业，促进农业生产经营的专业化、标准化、规模化。提高农业资源利用效率，大力发展生态农业、循环农业，推进农村节能减排，保护农村生态环境。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">（三）以发展生态旅游业为支柱，注入发展新活力。以红石镇和平水库为中心建设红色旅游文化产业项目，打造集旅游主题公园区、冰雪项目区、花卉观赏区、休闲度假区、医药保健区、蔬果种植体验区和中小药材产业区为一体的综合开发项目；依托柳条屯玫瑰红苹果采摘园、由家村康乐现代农业园区等农业旅游项目，建成一条集休闲、采摘、园艺一体的生态旅游线路；打造关岳庙、香瓜地等风光旅游景点，让良好生态成为乡村振兴支撑点。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">（四）以乡村振兴战略为总抓手，实现发展新局面。认真学习贯彻落实习近平总书记关于做好&ldquo;三农&rdquo;工作的重要论述精神，按照产业兴旺、生态宜居、乡风文明、治理有效、生活富裕的要求，抓重点、提质量、增动能、强基础，实现红石镇农业强、农民富、农村美的新局面。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
