//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">姜家店朝鲜族乡</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本概况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">姜家店朝鲜族乡总面积<span lang="EN-US">92.7</span>平方公里，辖<span lang="EN-US">10</span>个行政村，<span lang="EN-US">27</span>个自然屯，总户数共<span lang="EN-US">4087</span>户，总人口<span lang="EN-US">11184</span>人，实际在家人口<span lang="EN-US">3900</span>人，其中朝鲜族占人口总数的<span lang="EN-US">42%</span>，是柳河县朝鲜族聚居的少数民族建制乡镇之一。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡土地面积<span lang="EN-US">65000</span>亩，其中水田面积<span lang="EN-US">32000</span>亩。林地面积<span lang="EN-US">2600</span>公顷，林木覆盖率<span lang="EN-US">42.5</span>％，活立木蓄积量<span lang="EN-US">75</span>万立方米。境内有三统河、凉水河、后河、蛤喇河，流域面积<span lang="EN-US">232</span>平方公里；这里蕴藏着丰富的火山岩、火山渣，拥有独特的玄武岩地貌；这里拥有吉林省保存较好、规模较大的<span lang="EN-US">&ldquo;</span>五七<span lang="EN-US">&rdquo;</span>干校旧址，美丽丰富的自然景观和悠久深厚的历史文化底蕴是其尚未利用的宝贵财富。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">京几屯位于姜家店朝鲜族乡五星村，是历史悠久的朝鲜族村落，近年来，乡党委、政府结合当地实际情况，加大民俗旅游招商引资工作，美丽谷生态农场项目应运而生，项目以朝鲜族民宿为依托，将朝鲜族闲置房屋进行集中打造，并逐步向集生态农场，休闲观光、订制采摘等于一体的旅游项目发展，内设垂钓园、花海、采摘园、农牧区等。目前已投资<span lang="EN-US">200</span>万元，完成<span lang="EN-US">7</span>个民俗屋改造工作。为进一步推进民俗旅游项目发展，乡党委、政府投入资金<span lang="EN-US">100</span>万元完善五星村基础设施，新建京几屯水泥路<span lang="EN-US">1</span>公里、水渠<span lang="EN-US">500</span>米、塘坝一处，基础设施得到进一步完善。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">经勘探发现辖区内具有丰富的玄武岩资源，目前姜家店朝鲜族乡玄武岩企业有<span lang="EN-US">5</span>家，分别是通化中海玄武岩建筑材料有限公司、柳河县天佑石材场、柳河县天艺石材有限公司、柳辉石材场、众成玄武岩有限公司。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡共有四条主要河流分别是凉水河、三统河、蛤蜊河、后河。小一型水库<span lang="EN-US">1</span>座（姜家店水库），小二型水库<span lang="EN-US">3</span>座（三合、京畿、泰来水库），拦河坝<span lang="EN-US">13</span>座，较大塘坝<span lang="EN-US">8</span>座。姜家店水库，设计库容<span lang="EN-US">89</span>万立方米，目前达到<span lang="EN-US">60</span>万立方米，低水位<span lang="EN-US">134.2</span>米，校核水位<span lang="EN-US">393</span>米，正常水位<span lang="EN-US">392</span>米。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">姜家店朝鲜族乡农业资源丰富，种植业基础牢固。<span lang="EN-US">2020</span>年粮食作物总产量<span lang="EN-US">36915</span>吨，其中稻谷产量<span lang="EN-US">13485</span>吨、玉米产量<span lang="EN-US">23430</span>吨。现有农业合作社<span lang="EN-US">68</span>个。乡内有国家级水稻种植标准化种植基地、省级农产品加工示范区等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水稻种植产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">以绿优米种植为基础，稻米产业发展势头强劲。目前，我乡有稻米企业<span lang="EN-US">11</span>家，自我品牌<span lang="EN-US">10</span>家，<span lang="EN-US">2021</span>年我乡将继续利用特有<span lang="EN-US">&ldquo;</span>姜家店大米<span lang="EN-US">&rdquo;</span>中国地理标识保护产品及吉林省气象局和省农科院颁发的<span lang="EN-US">&ldquo;</span>姜家店乡大米独特小气候认证<span lang="EN-US">&rdquo;</span>优势条件，大力发展稻米产业。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">玄武岩产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">以玄武岩资源为依托，深加工项目潜力巨大。全力盘活玄武岩企业，推进玄武岩深加工项目落实，引导玄武岩企业开发建设玄武岩拉丝项目，与军工企业联手，生产或配套生产军工产品，不断提升产品附加值。<span lang="EN-US">2021</span>年，积极引导玄武岩生产加工企业拉伸产业链条，推动天艺石材和天佑石材寻求合作伙伴，转变生产方式，由粗放型向科技型转变，推进玄武岩产品优化升级；帮助协调中海玄武岩和众成石材完善相关证照的审批进度，盘活福宽石材，主动提升服务意识，使企业尽快达产达效，进一步扩大产能。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">加快农业结构调整。重点做好稻米品种的引进和改良，积极主动走出去，学习先进的种植技术，不断改善产业结构，拉长产业链。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">发展特色旅游业。依托稻米产业，重点推进乐享田园综合体建设项目，发展特色强、内涵丰富的朝鲜族特色旅游点，做好生态文章，打造<span lang="EN-US">&ldquo;</span>生态休闲旅游乡镇<span lang="EN-US">&rdquo;</span>。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">进一步加大税收征管力度，聚焦项目建设、固定资产投资、企业经营运行，强化税收征缴，做到应收尽收，保障财政收入；依托稻米产业、玄武岩产业及朝鲜族民俗特色，与企业深入交流，全面推进<span lang="EN-US">&ldquo;</span>最多跑一次<span lang="EN-US">&rdquo;</span>工作，主动上门服务，帮助企业发展壮大。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
