//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">凉水河子镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇位于五县一市交接处，全镇幅员面积<span lang="EN-US">569.08</span>平方公里，辖<span lang="EN-US">10</span>个行政村，<span lang="EN-US">29</span>个自然屯，总人口<span lang="EN-US">15858</span>人，是国家级生态镇、省级卫生镇、省级文明村镇。县级公路驼靖线、三回线，省级营白公路贯穿全境，辉临高速穿境而过，并设有入口，距镇政府所在地<span lang="EN-US">2.5</span>公里。耕地面积<span lang="EN-US">73760</span>亩，其中水田<span lang="EN-US">7477.5</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">境内水资源丰富，以凉水河、哈泥河为主要干流，境内河流总长<span lang="EN-US">257.6</span>千米，流域面积<span lang="EN-US">517.15</span>平方公里。凉水镇流域面积<span lang="EN-US">20</span>平方公里以上河流<span lang="EN-US">9</span>条、流域面积<span lang="EN-US">20</span>平方公里以下的河流<span lang="EN-US">36</span>条。现有水库和塘坝<span lang="EN-US">8</span>座。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇属于柳河县东侧边陲山区，龙岗山脉，沟谷纵横，森林茂密，蕴育了丰富的自然资源，野生动植物资源达<span lang="EN-US">700</span>多种，森林覆盖率达<span lang="EN-US">85%</span>。辖区林地面积<span lang="EN-US">25.88</span>万亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇地下水资源十分丰富，全镇矿泉水资源范围约为<span lang="EN-US">16.62</span>平方公里，日涌量约为<span lang="EN-US">4700</span>吨，矿泉水水源位于距镇区<span lang="EN-US">12</span>公里处，日流量<span lang="EN-US">250</span>吨，经国家饮用产品质量监督检验中心鉴定，均达到矿泉水界限指标的要求。凉水河子镇矿产资源丰富，现已发现金矿、铁矿、硅石、钾石、玄武岩等矿产资源<span lang="EN-US">20</span>余种，经省地勘院勘探，金矿储量约<span lang="EN-US">5</span>吨、铁矿储量约<span lang="EN-US">140</span>万吨、硅石储量约<span lang="EN-US">20</span>万吨、钾石储量约<span lang="EN-US">10</span>万吨、玄武岩储量约<span lang="EN-US">163</span>立方米，品位都很高。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全镇耕地面积<span lang="EN-US">73760</span>公顷，主要粮食作物有玉米、水稻、大豆、其次为杂粮和薯类。凉水河子镇生猪存栏<span lang="EN-US">3532</span>头；黄牛存栏<span lang="EN-US">6356</span>头；蛋鸡存栏<span lang="EN-US">140000</span>只。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">5.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇一年四季风景如画，春观山花浪漫，夏享哈泥清爽，秋赏红叶漫山，冬感冰雪激情，又具有浓厚的红色文化和餐饮文化，具备绿色、白色、红色和金色&ldquo;四色&rdquo;旅游之禀赋，抗联遗址、独特的冰雪资源在全境彰显。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产开发业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇工业企业以矿泉水和铁矿企业为主，现有矿泉水企业<span lang="EN-US">1</span>家、铁矿企业<span lang="EN-US">2</span>家正在生产。吉林省天池泉矿泉水有限公司，<span lang="EN-US">1997</span>年企业投入生产，占地面积<span lang="EN-US">1.4</span>万平方米，厂房面积<span lang="EN-US">8000</span>平方米，年生产瓶装水、桶装水<span lang="EN-US">30</span>万件；柳河县海华矿业有限公司位于凉水河子镇回头沟村，占地面积<span lang="EN-US">56</span>亩，建筑面积<span lang="EN-US">4500</span>平方米，主要生产铁精粉；柳河县恒亿矿业有限公司位于凉水河子镇腰站村，公司成立于<span lang="EN-US">2013</span>年，占地面积<span lang="EN-US">45</span>亩，建筑面积<span lang="EN-US">1500</span>平方米，年开采能力<span lang="EN-US">2</span>万吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">乡村旅游产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇的乡村旅游主要以冰雪和红色旅游为主。龙岗绿水山庄占面积<span lang="EN-US">3.5</span>万平方米，总建筑面积<span lang="EN-US">2.265</span>万平方米。该项目集健康养生、生态观光、温泉疗养、冰雪娱乐、快乐垂钓为一体，日可接待游客<span lang="EN-US">3000</span>人，可接待<span lang="EN-US">200</span>人同时用餐；凉水河子抗联纪念馆建于<span lang="EN-US">2020</span>年，占地面积<span lang="EN-US">2000</span>平方米，建筑面积<span lang="EN-US">700</span>平方米，设有教学区、展览区、休息区，馆内展品<span lang="EN-US">159</span>件，该纪念馆已被列入杨靖宇干部学院教学点。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇的特色产业以林蛙、松籽、山野菜产业为主。一是林蛙产业，我镇区域内人工养殖林蛙户<span lang="EN-US">39</span>户，养殖户占林地放养面积<span lang="EN-US">13600</span>公顷，每年放养林蛙约<span lang="EN-US">1.6</span>亿只，每年秋季回捕林蛙成蛙在<span lang="EN-US">6</span>万斤左右。二是松籽产业，我镇共有<span lang="EN-US">120</span>户左右的农户承包红松果林，承包范围包括本镇辖区、吉林省、黑龙江省部分地区，其中本镇辖区内的承包面积在<span lang="EN-US">9000</span>亩以上；因我镇松子产量大、品质高，每年秋季红松籽都被外地客商抢购一空。三是山野菜产业，我镇的山野菜品种主要是蕨菜、大叶芹、刺五加、刺嫩芽、薇菜、猴腿、龙须菜等<span lang="EN-US">40</span>余种，年采集量达<span lang="EN-US">1500</span>吨以上。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">凉水河子镇将紧紧围绕&ldquo;生态立镇、工业强镇、旅游兴镇、产业旺镇、民生和镇&rdquo;的总体战略目标，着眼生态优势亮本底，挖掘三产潜力抢机遇，以项目建设为抓手，突出工业主导，搞好旅游业、服务业升级，推动农业产业化发展，加快乡村振兴建设步伐，实现生态环境改善、人民生活水平提升、社会和谐稳定，不断提高综合经济实力和可持续发展动力，推动经济社会全面进步。开发水资源，做好矿泉水文章；借助生态资源，做好旅游文章；深挖红色资源，做好传承文章；打造产业集群，做好特色文章，大力发展食用菌种、特色养殖项目、特色农产品加工，闯出特色，唱响品牌。凉水河子镇将结合自然、人文、交通等条件优势，努力打造休闲宜居镇、旅游度假镇。对于落户凉水河子镇企业，在土地、税收等方面将实行&ldquo;一事一议&rdquo;的优惠政策。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
