//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">柳南乡</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳南乡位于柳河县西南部，距柳河县城<span lang="EN-US">38</span>公里，距通化市区<span lang="EN-US">32</span>公里，距通化机场<span lang="EN-US">13</span>公里。全乡幅员面积<span lang="EN-US">150</span>平方公里，耕地面积<span lang="EN-US">5883</span>公顷<span lang="EN-US">,</span>森林面积<span lang="EN-US">8736</span>公顷。辖<span lang="EN-US">7</span>个行政村，<span lang="EN-US">15</span>个自然屯，户籍人口所在数<span lang="EN-US">12059</span>人，实际人口居住数在<span lang="EN-US">7797</span>人。乡内有旱田约<span lang="EN-US">65000</span>亩，水田约<span lang="EN-US">4500</span>亩，另有果园约<span lang="EN-US">200</span>公顷，林地约<span lang="EN-US">800</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">我乡位于通化市和柳河县交界处，地处交通要道，我乡充分利用独特的区位优势、交通优势和产业优势，以港务区征地建设这一主线，带动烤烟、中草药种植、大辣椒种植、果蔬大棚、畜牧业养殖<span lang="EN-US">5</span>个产业共同发展，各村屯根据位置情况、资源情况，进行合理配置农产品加工业，精心培育运输业和养殖业。种植业方面：大力发展马鹿沟村、辛家村、柞木村烟草种植基地，用现代科技手段减焦除害，推进烟叶生产提质升级，走&ldquo;园区<span lang="EN-US">+</span>基地<span lang="EN-US">+</span>农户&rdquo;模式，种植面积稳定在<span lang="EN-US">2000</span>亩左右，使之成为柳河县内重要的烟草生产基地。建设以柞木村、六合村为中心的林下参种植观光基地，带动全乡林下参产业的发展。依托以辛家村、通沟村、吕家堡村为主发展棚膜蔬菜基地，使柳南成为通化市的&ldquo;菜篮子&rdquo;。畜牧业方面：目前我乡牛的存栏量在<span lang="EN-US">3100</span>头左右，猪的存栏量在<span lang="EN-US">3800</span>头左右，羊的存栏量在<span lang="EN-US">1400</span>头左右，打造马鹿沟村、吕家堡村、辛家村<span lang="EN-US">10-15</span>个畜牧养殖基地，使之成为通化市及周边地区的&ldquo;肉案子&rdquo;。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳南乡现有烤烟<span lang="EN-US">860</span>亩，多集中在铁东，柞木，辛家村，在烟草方面淘汰劣户、兼并小户、帮助烟户调整和选择适宜种植地块，争取加快推进烤烟基地项目建设，产业规模逐年递增，计划<span lang="EN-US">2035</span>年达到<span lang="EN-US">2000</span>亩，建设烟叶园区。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳南乡现有园参<span lang="EN-US">800</span>亩，结合县委、县政府生态环境治理力度加大，全面禁止山上种植，人参生产将转移大田生产，计划发展园参<span lang="EN-US">3000</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">依托农村经济合作社，发挥农民经纪人的作用，大力发展水果萝卜、反季节白菜、香菜种植，蜜蜂养殖等产业，<span lang="EN-US">2020</span>年末发展水果萝卜种植<span lang="EN-US">300</span>亩、反季节白菜、香菜种植<span lang="EN-US">6000</span>亩，蜜蜂养殖<span lang="EN-US">200</span>箱，带动农户<span lang="EN-US">1300</span>户。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">结合我乡的区位优势和实际情况，柳南乡努力打造成通化市的&ldquo;肉案子&rdquo;、&ldquo;菜篮子&rdquo;，加大种养殖业发展力度，柳南乡现有养殖小区和大户<span lang="EN-US">60</span>户（猪<span lang="EN-US">18</span>户、鸡<span lang="EN-US">3</span>户、牛<span lang="EN-US">17</span>户、羊<span lang="EN-US">22</span>户）。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 14.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">目前我乡招商引资项目<span lang="EN-US">3</span>个，均为港务区基建工程项目，分别是供水厂一期，项目投资<span lang="EN-US">4.64</span>亿，占地面积<span lang="EN-US">1.57</span>万平方米。消防应急中心，总投资<span lang="EN-US">2.22</span>亿，占地面积<span lang="EN-US">4.9</span>万平方米。污水处理厂一期，总投资<span lang="EN-US">1.76</span>亿元，占地面积<span lang="EN-US">7.65</span>万平方米，目前三个项目都已经开工建设，预计在<span lang="EN-US">2021</span>年<span lang="EN-US">11</span>月份竣工。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
