//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">罗通山镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">罗通山镇地处吉林省通化市柳河县东北部，距县城所在地<span lang="EN-US">45</span>公里，全境幅员面积<span lang="EN-US">124.5</span>平方公里。西北背倚风景秀丽的国家<span lang="EN-US">AAAA</span>级风景旅游区罗通山，东北与辉南的样子哨镇、东南与姜家店朝鲜族乡隔河相望；西南与时家店乡接壤，西北与亨通镇接壤，北与圣水镇毗邻。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">罗通山镇下辖<span lang="EN-US">7</span>个行政村，<span lang="EN-US">20</span>个自然屯，总人口<span lang="EN-US">1.1</span>万人。在册耕地总面积<span lang="EN-US">4.7</span>万亩，其中水田<span lang="EN-US">0.8</span>万亩，旱田<span lang="EN-US">3.9</span>万亩。罗通山镇是以农业为主的小乡镇，没有较大工业企业。<span lang="EN-US">2020</span>年总产值<span lang="EN-US">12762</span>万元，其中农业产值<span lang="EN-US">6602</span>万元，非农产值<span lang="EN-US">6160</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">全镇幅原面积<span lang="EN-US">124.5</span>平方公里，共有耕地<span lang="EN-US">6713.54</span>公顷，其中水田<span lang="EN-US">636.68</span>公顷，旱田<span lang="EN-US">6076.86</span>公顷。林地面积<span lang="EN-US">4934.65</span>公顷，其中有林地<span lang="EN-US">4908.40</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">玄武岩资源：罗通山域内蕴藏大量的玄武岩资源，主要分布在三统河沿岸的自立村，此前曾有宝星玄武岩石材加工有限公司在自立村进行板材加工，现已停产。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">石膏矿石资源：石膏矿石主要分布在福民村水洞屯和通沟村通北屯。已有大通矿业有限公司和谊兴矿业有限公司两家投资开采，但均未通过安全生产验收，都没正式投入生产。现谊兴矿业已处于停产关闭状态，已停止井下排水；大通矿业尚维持井下排水作业。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">水力资源：三统河罗通山段，由胜利村东河屯入境，至自然村河口屯出境，全长共<span lang="EN-US">19.8</span>公里。在自立村境内河段落差较大，在此，建有两座水力发电站。珩阳逸景大峡谷漂流项目就建在大通沟水利发电站至河口屯之间。另外，罗通山境内还有丰富的涌泉资源，尤其自立村东兴屯和砬子村中兴屯最具代表性，涌泉水质好、水量足，经年不息，是进行饮用山泉水开发、冷水鱼养殖的理想之所。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">旅游资源：罗通山境内有国家<span lang="EN-US">4A</span>级风景区罗通山，山上有国家级重点文物保护单位&mdash;&mdash;罗通山城遗址。罗通山还是吉林省野生珍稀植物自然保护区，山高林密、崖险洞幽，自然景观与人文景观完美融合，是追溯历史、品味自然，放飞心灵的理想之所。新建的逸景大峡谷漂流项目已经成功试漂，将成为省内漂流项目新晋的打卡地。正在谋划中的砬子村乡村旅游项目、福民村&ldquo;福民雪村&rdquo;项目，都在积极推进中。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">人力资源：罗通山镇现有人口<span lang="EN-US">1.1</span>万人，其中劳动力资源数<span lang="EN-US">6520</span>人。平均力工工资约<span lang="EN-US">130</span>元<span lang="EN-US">/</span>日左右；木、瓦匠及其他技术工<span lang="EN-US">300</span>元<span lang="EN-US">/</span>日左右。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">罗通山镇是一个农业为主的小乡镇，没有工业企业。村民主要从事种植业与养殖业。近年来，随着罗通山景区开发的持续深入，珩阳逸景大峡谷漂流项目逐步完善，罗通山镇的旅游产业正在迅速崛起，&ldquo;福民雪村&rdquo;项目也正在谋划推进之中，各种旅游产品正在形成聚集，涌入罗通山镇的外地游客将越来越多，罗通山镇即将步入旅游产业发展的快车道。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">柳河珩阳逸景康养旅游度假小镇项目由吉林省珩阳逸景实业有限公司于<span lang="EN-US">2019</span>年投资建设，预计总投资<span lang="EN-US">80000</span>万元<span lang="EN-US">,</span>项目位于吉林省通化市柳河县罗通山镇自立村，本项目总占地面积<span lang="EN-US">14</span>万平方米，总建筑面积<span lang="EN-US">4715</span>平方米<span lang="EN-US">,</span>项目按主要内容规划分为<span lang="EN-US">6</span>个功能区：客服和新区、观光农业区<span lang="EN-US">,</span>滑雪与滑草区、戏水乐园区、养老度假区及漂流区。预计建成后年产值达<span lang="EN-US">10000</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">发展方向：未来罗通山镇的发展方向就是发展旅游产业。以旅游产业开发做主导，带动餐饮、农家乐、民宿、休闲娱乐等配套服务产业、生态观光农业、有机农产品加工企业等共同发展，形成&ldquo;吃、住、玩、购、游&rdquo;旅游全产业链条，打造罗通山镇&ldquo;围旅&rdquo;经济新格局。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">合作意向：独资或股份制（以旅游资源入股）合作开发旅游产品、打造旅游服务产业、建设生态观光农业系统、打造文艺演出平台等。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
