//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">圣水镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">圣水镇于柳河县东北部，距县城<span lang="EN-US">29.5</span>公里，地理位置优越，农业资源丰富，是柳河县有名的农牧大镇，北与梅河口市新合镇接壤，南与罗通山镇毗邻，西与亨通镇交界，东与辉南县样子哨镇相邻。全镇幅员面积<span lang="EN-US">225</span>平方公里，地势南高北低，处于缓丘陵地带，海拔<span lang="EN-US">320</span>～<span lang="EN-US">937</span>米，风景秀丽的罗通山古城，座落在圣水境内南端。全镇共有<span lang="EN-US">21</span>个行政村<span lang="EN-US">57</span>个自然屯。乡村从业人员<span lang="EN-US">12819</span>人，其中农业从业人员<span lang="EN-US">10450</span>人。共有<span lang="EN-US">30</span>个党支部，有<span lang="EN-US">872</span>名党员。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源：<span lang="EN-US">2020</span>年，圣水镇农作物总播种面积为<span lang="EN-US">8044</span>公顷。其中，粮食作物播种面积为<span lang="EN-US">7967.7</span>公顷。玉米播种面积为<span lang="EN-US">6413</span>公顷；大豆播种面积为<span lang="EN-US">21.7</span>公顷；水稻播种面积为<span lang="EN-US">1467</span>公顷；马铃薯栽种为<span lang="EN-US">45</span>公顷；小杂粮播种面积为<span lang="EN-US">66</span>公顷；红薯栽种面积为<span lang="EN-US">15</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特产：主要经济作物有蒲公英、防风、五味子、苍竹等。全镇经济作物有林下参面积<span lang="EN-US">840</span>余亩，总产值<span lang="EN-US">3360</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">林业：圣水镇林地面积<span lang="EN-US">11277</span>公顷，幼林抚育<span lang="EN-US">200</span>公顷，育苗面积<span lang="EN-US">24</span>公顷，山地育苗<span lang="EN-US">46</span>公顷，蚕场采伐审批面积<span lang="EN-US">11</span>公顷。巩固林业生态建设成果，补植造林<span lang="EN-US">180</span>公顷，林业生态建设面积保存率<span lang="EN-US">100%</span>。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">牧业：以吉祥牧业为龙头，全镇畜牧业以肉鸡、生猪、羊、牛为主，<span lang="EN-US">2020</span>年养猪户<span lang="EN-US">505</span>户，其中备案养殖场<span lang="EN-US">3</span>家。年出栏育肥猪<span lang="EN-US">3467</span>头，年末存栏<span lang="EN-US">3886</span>头；养牛户<span lang="EN-US">505</span>户，年出栏牛<span lang="EN-US">286</span>头，年末存栏量<span lang="EN-US">1996</span>头；养羊户<span lang="EN-US">37</span>户，共养羊<span lang="EN-US">303</span>只，年出栏<span lang="EN-US">695</span>只；家禽散养饲养量<span lang="EN-US">22.838</span>千只。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利水产：圣水镇拥有小（<span lang="EN-US">I</span>）型水库<span lang="EN-US">2</span>座（东方红、荆大院），小（<span lang="EN-US">II</span>）型水库<span lang="EN-US">12</span>座（五大家南、郑福东、永兴、崔家街、陶家街、王大院、陆崴子、大卜子、二岔沟、龙王庙、窝集沟、集安屯），塘坝<span lang="EN-US">107</span>座。水域面积<span lang="EN-US">190</span>公顷，水库塘坝总蓄水量<span lang="EN-US">212</span>万方，集水面积<span lang="EN-US">53.97</span>平方公里；有电灌站<span lang="EN-US">15</span>个。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况：</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">、旅游业：以罗通山风景区为依托，已建成小泉眼村民宿及附属设施，草莓采摘园区，下步新建旅游项目康养中心建设（梦幻之门、游客接待中心、水上游乐园、攀岩基地、森林康养师培训中心、两大康养酒店，一个主题公园、红色历史博物馆，康养体验特色区、民俗文化讲堂区、特色休闲餐饮区、服饰工艺礼品区、公园配套服务区及康养医院<span lang="EN-US">1</span>座）。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">、畜牧业：以吉祥牧业有限公司为龙头企业发展肉鸡养殖产业，吉祥牧业现有种鸡场<span lang="EN-US">1</span>处、养殖场<span lang="EN-US">2</span>处，<span lang="EN-US">2021</span>年申请扶贫资金在圣水镇五大家村新上标准化种鸡扩繁项目。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">、矿产业：圣水镇原有太平川马安山采石场、康宁采石场、泉眼采石场。因环保等限制<span lang="EN-US">3</span>处采石场现已停产整顿，正在招商引进先进生产设备进行重启。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">&ldquo;十四五&rdquo;期间，圣水镇将严格贯彻落实县委&ldquo;三个五&rdquo;发展战略，始终坚持以高质量发展为核心，依托域内种养殖产业基础及良好的生态旅游资源，积极推动&ldquo;一游、两带、三区&rdquo;一二三产业立体融合发展。一是依托&ldquo;一游&rdquo;罗通山旅游风景区开展特色民宿、观光农业、网红花海、休闲垂钓等配套型旅游开发项目；二是围绕特色种植和特种养殖的&ldquo;两带&rdquo;推动杂粮种植及鸡鸭鹅、生猪及梅花鹿、鸵鸟为主的种养殖产业快速发展；三是全力构建&ldquo;三区&rdquo;镇域经济增长极，即：重启盘活为主的企业示范区，加快推进淹制速冻为主的加工示范区，建设以直播带货为主的电子商务示范区。圣水镇党委和人民政府欢迎社会各界有识之士莅临圣水共谋发展。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
