//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">时家店乡</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">时家店乡位于柳河县东部，属半山区，距县城<span lang="EN-US">30</span>公里。东临姜家店朝鲜族乡，西临柳河镇，南临孤山子镇、驼腰岭镇，北与亨通镇、罗通山镇接壤。幅员面积<span lang="EN-US">110.1</span>平方公里。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡共有<span lang="EN-US">8</span>个行政村，<span lang="EN-US">1</span>个社区，<span lang="EN-US">20</span>个自然屯，共有<span lang="EN-US">4645</span>户，<span lang="EN-US">12498</span>口人，其中：男性人口<span lang="EN-US">6584</span>人，女性人口<span lang="EN-US">5914</span>人。<span lang="EN-US">2020</span>年度全乡总收入<span lang="EN-US">11441</span>万元，其中农业总收入<span lang="EN-US">4276</span>万元、林业收入<span lang="EN-US">1033</span>万元、牧业收入<span lang="EN-US">3586</span>万元、渔业收入<span lang="EN-US">473</span>万元、工业收入<span lang="EN-US">729</span>万元、运输业<span lang="EN-US">319</span>万元、建筑业<span lang="EN-US">144</span>万元、商饮业<span lang="EN-US">286</span>万元、服务业<span lang="EN-US">99</span>万元、其他<span lang="EN-US">496</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡耕地面积<span lang="EN-US">4208</span>公顷耕地面积<span lang="EN-US">4208</span>公顷，其中旱田<span lang="EN-US">2618</span>公顷；水田<span lang="EN-US">1590</span>公顷。水果种植面积<span lang="EN-US">25.3</span>公顷。全乡森林覆盖率为<span lang="EN-US">49%</span>。造林面积<span lang="EN-US">8747.6</span>亩，有主伐<span lang="EN-US">11.94</span>公顷，出材<span lang="EN-US">1359</span>立方米。四旁植树<span lang="EN-US">21000</span>株。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">人力资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡共有劳动力<span lang="EN-US">7620</span>人，其中：女劳动力<span lang="EN-US">3718</span>人，农业劳动力<span lang="EN-US">5228</span>人，工业劳动力<span lang="EN-US">2392</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">有中型水库时家店水库<span lang="EN-US">1</span>座、小一型水库<span lang="EN-US">1</span>座、小二型水库<span lang="EN-US">3</span>座、塘坝<span lang="EN-US">15</span>座。其中：时家店水库总库容量<span lang="EN-US">1496</span>万立方米，库区周长<span lang="EN-US">9</span>公里，占地面积<span lang="EN-US">3200</span>亩，积水面积<span lang="EN-US">59.7</span>平方公里，库内生长鳙、鲢、草、青、鲫、鲶、黑等<span lang="EN-US">10</span>多个淡水鱼种，年产淡水鱼<span lang="EN-US">12</span>万斤，还出产河蚌、田螺等野生美味。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全乡耕地面积<span lang="EN-US">4208</span>公顷，主要粮食作物有玉米、水稻、大豆、其次为杂粮和薯类。<span lang="EN-US">2020</span>年度全乡蔬菜播种面积<span lang="EN-US">96</span>公顷，产量<span lang="EN-US">3106</span>吨；水果种植面积<span lang="EN-US">25.3</span>公顷，产量<span lang="EN-US">158</span>吨。其中：苹果种植面积<span lang="EN-US">3.3</span>公顷，产量<span lang="EN-US">2</span>吨；梨种植面积<span lang="EN-US">2</span>公顷，产量<span lang="EN-US">4</span>吨；葡萄种植面积<span lang="EN-US">6.5</span>公顷，产量<span lang="EN-US">143</span>吨；松子种植面积<span lang="EN-US">150</span>公顷，产量<span lang="EN-US">7</span>吨；烤烟种植面积<span lang="EN-US">10</span>公顷，产量<span lang="EN-US">27</span>吨。发展柞蚕<span lang="EN-US">160</span>公顷，产量<span lang="EN-US">75.2</span>吨；牛存栏<span lang="EN-US">1979</span>头，猪存栏<span lang="EN-US">790</span>头，家禽<span lang="EN-US">369000</span>只。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">时家店乡富含丰富的矿产资源，其中以出产石灰石和石膏为主。石灰石中碳酸钙含量高达<span lang="EN-US">51%</span>以上，属高钙石灰岩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">5.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">时家店水库三面环山，山水交映，每逢春季，灰鹤、野鸭等野生鸟类至此栖息繁衍。周边山林郁郁葱葱，山间溪流潺潺，林下不乏野果山珍。这里的<span lang="EN-US">&ldquo;</span>水<span lang="EN-US">&rdquo;</span>与罗通山的<span lang="EN-US">&ldquo;</span>山<span lang="EN-US">&rdquo;</span>可谓交相呼应、<span lang="EN-US">&ldquo;</span>山水一线<span lang="EN-US">&rdquo;</span>，是供度假旅游、休闲养生的理想之地。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">冰雪旅游产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">依托时家店中型水库，<span lang="EN-US">2016</span>年时家店乡成立了旅游综合开发有限公司，打造了时家店冰雪嘉年华，该项目规划占地面积<span lang="EN-US">2</span>平方公里，距柳河县城<span lang="EN-US">20</span>公里，距通梅一级公路<span lang="EN-US">6</span>公里，距通化机场<span lang="EN-US">30</span>公里。日最多可接纳游客<span lang="EN-US">2000</span>人次，年积雪期<span lang="EN-US">150</span>天，可供滑雪期<span lang="EN-US">140</span>天。冰雪嘉年华目前共开展滑雪、滑冰、冲浪雪圈、雪地摩托、卡丁车、冰车、冰陀螺、马拉爬犁、飞碟碰碰车、雪地坦克、雪迷宫、儿童戏雪、雪地足球、雪地拔河、雪雕观赏、农家乐等<span lang="EN-US">20</span>多个项目，有综合服务场所<span lang="EN-US">2</span>处，建筑面积<span lang="EN-US">1000</span>平方米，建有<span lang="EN-US">2</span>处停车场，可接待<span lang="EN-US">300</span>人用餐。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">石灰石矿产开发产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县天翊钙业有限公司位于时家店乡长兴村项家屯，占地面积<span lang="EN-US">66</span>亩，石灰石储量为<span lang="EN-US">12.13</span>亿吨，碳酸钙含量高达<span lang="EN-US">51%</span>以上，属高钙石灰岩。采用国家石灰行业协会大力推广的<span lang="EN-US">&ldquo;</span>中石立窑<span lang="EN-US">&rdquo;</span>及河北厂家研发的新型环保节能立窑技术标准，建设自动控制型直筒混烧石灰窑，配套建设原料和成品输送、筛选、贮料、装卸、环保除尘设施及项目总体工作系统，不仅节能环保，增加产业附加值，而且对当地石灰石资源进行了整合开发。<span lang="EN-US">2020</span>年企业销售收入<span lang="EN-US">1.15</span>亿元，直接安排就业人员<span lang="EN-US">170</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">时家店乡未来计划引进域外资本，投资打造环时家店水库夏季水上乐园、冬季大型冰上运动娱乐及特色民宿、农家乐类型旅游类项目。期待外界有识之士，能莅临参观考察，交流对接。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
