//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">驼腰岭镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇位于柳河县城东南部，幅员面积<span lang="EN-US">132</span>平方公里，辖<span lang="EN-US">18</span>个行政村、<span lang="EN-US">32</span>个自然屯，有<span lang="EN-US">2</span>个朝鲜族村。全镇共有<span lang="EN-US">5469</span>户<span lang="EN-US">13890</span>人，常住人口<span lang="EN-US">7616</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇是连接通化、白山、梅河口的重要交通枢纽，是全县重要的烟叶生产基地、建材生产基地和葡萄产业发展基地，是通化市最大的粮食集散地，省级卫生乡镇、省级平安畅通乡镇、通化市乙级经济强镇。我们充分发挥区位优势，坚持以矿产资源、粮食加工企业为龙头，探索发展优质稻米、中草药等特色产业集中连片、规模高效的新兴产业经营模式。烤烟、优质稻米、中草药、木耳种植，柞蚕、生猪养殖等多元化富民产业发展格局日趋完善。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇矿产资源丰富，石灰矿、石矿等资源储量较大，开发利用价值较高。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇根据各村屯特点，持续抓好农村人居环境整治，着力构建基础设施健全、生态宜居的重点示范村。依托扶贫产业园区，打造以杨家、黎明、宝善为中心的生态小镇中转枢纽，板庙村村史、民俗旅游生态线，逐步构筑&ldquo;一村一站&rdquo;&ldquo;一河一景&rdquo;&ldquo;一路一品&rdquo;大格局。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇共有耕地面积<span lang="EN-US">38854.5</span>亩，水田面积<span lang="EN-US">8995</span>亩，经济作物面积<span lang="EN-US">5000</span>亩，其中：烟叶<span lang="EN-US">1854</span>亩，大豆<span lang="EN-US">210</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇林业资源分布广泛，全镇林地总面积<span lang="EN-US">57180</span>亩。天然树种主要有红松、柞、杨、红豆杉、槐、刺楸、水曲柳、黄柏等。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇水资源充沛，辖区内流域总面积<span lang="EN-US">131.5</span>平方公里，河流总长度<span lang="EN-US">72.9</span>公里。共有大小河流<span lang="EN-US">19</span>条，其中：流域面积<span lang="EN-US">20</span>平方公里以上河流<span lang="EN-US">3</span>条，分别是三统河驼腰岭段、南甸心河、大荒沟河。共有水库<span lang="EN-US">6</span>座，塘坝<span lang="EN-US">6</span>座。其中：小一型水库<span lang="EN-US">2</span>座，小二型水库<span lang="EN-US">4</span>座。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇现有矿产资源企业<span lang="EN-US">2</span>家，分别是：盛宝石灰石矿及省矿。&ldquo;十四五&rdquo;期间，我们将稳步推进现有矿产资源整合。计划投入资金<span lang="EN-US">6000</span>万元打造盛宝石灰石矿产业集群，促进矿业开发向精深加工方向发展。整合项目完成后，可增加<span lang="EN-US">1400</span>万采矿量，开采石子<span lang="EN-US">60</span>万立，实现生产总值<span lang="EN-US">3000</span>万元。省矿吉森丰华采石场承包合同至<span lang="EN-US">2021</span>年结束，可产石子<span lang="EN-US">12.7</span>万立，产值<span lang="EN-US">635</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">粮食生产、仓储、运输业</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">现有稻米生产企业、合作社<span lang="EN-US">12</span>家，自主品牌<span lang="EN-US">5</span>个。驼腰岭镇粮食仓储运输业发达，现有规模型企业<span lang="EN-US">4</span>家，恒通粮食物流年生产量约<span lang="EN-US">7</span>万吨，年产值<span lang="EN-US">1.75</span>亿元；福军玉米烘干加工厂年生产量约<span lang="EN-US">2</span>万吨，年产值<span lang="EN-US">5000</span>万元；钟升粮食收储年生产量约<span lang="EN-US">6</span>万吨，年产值<span lang="EN-US">1.5</span>亿元；仓泰粮油年生产量约<span lang="EN-US">3</span>万吨，年产值<span lang="EN-US">7500</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色中草药材</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">驼腰岭镇中草药材种植面积达<span lang="EN-US">2000</span>余亩，集中分布在东兴村、高油村，主要种植蒲公英、天南星、苏子等品种。近年来，镇政府不断加大对万顺苏子种植合作社的扶持力度，以建设规范化、村集体<span lang="EN-US">+</span>公司<span lang="EN-US">+</span>合作社<span lang="EN-US">+</span>农户的方式，以点带面，带动全镇<span lang="EN-US">18</span>个行政村的村集体经济项目。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">依托环绕区位优势，以发展农产品加工为主线，中草药种植、矿产资源开发和优质稻米生产线为着力点，壮大现有企业，积极招引，以产业振兴为基础，促进镇域经济发展。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
