//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">五道沟镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">五道沟镇地处柳河县南部，因位于三统河西北第五条沟而得名，幅员面积<span lang="EN-US">187</span>平方公里，辖<span lang="EN-US">2</span>个社区、<span lang="EN-US">16</span>个行政村，<span lang="EN-US">23</span>个独立核算单位，<span lang="EN-US">37</span>个自然屯。林地面积<span lang="EN-US">9.01</span>万亩，耕地面积<span lang="EN-US">8.8</span>万亩，其中旱田面积<span lang="EN-US">8.1</span>万亩，水田面积<span lang="EN-US">0.75</span>万亩。总户数<span lang="EN-US">6160</span>户，总人口<span lang="EN-US">22118</span>人。距通化三源浦机场<span lang="EN-US">15</span>公里，梅集铁路穿境而过<span lang="EN-US">,</span>集双高速、<span lang="EN-US">303</span>国道等公路纵横交错。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">河道属松花江流域，松花江二级支流三统河（中段）自西南向东北流经境内<span lang="EN-US">14.8</span>千米，有数条支流，流域面积<span lang="EN-US">186.2</span>平方千米；</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">五道沟镇境内已探明地下矿藏有石灰石、花岗岩、硅石、草炭土、铜、铁、煤等；石灰石、草炭土储量大；尚有近亿立方米储量的泥炭土资源有待开发。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">天然树种主要有红松、落叶松、水曲柳、柳、柞、桦等；野果类主要有山杏、李子、山葡萄、榛子、山核桃、山梨等；野生药材主要有山参、细辛、桔梗、贝母、柴胡、党参、五味子、景天、地龙骨、龙胆草等；山野菜主要有蕨菜、薇菜、刺嫩芽等；野生菌类主要有榛蘑、松树伞等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">4</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">、野生动物资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">野生动物主要有狍子、雉、刺猬、榛鸡、花鼠、貉子、狐狸、林蛙、兔等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">1</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">、旅游产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">镇内有丰富的红色旅游资源。日俄战争时期，博雅沟村民刘宽吹响了抗击外侮的号角<span lang="EN-US">;</span>东北抗联史册上，蔺秀义组建的柳河游击连，让日伪军闻风丧胆<span lang="EN-US">;</span>解放战争时期，萧劲光大将取得&ldquo;柳南大捷&rdquo;。红色历史造就了五道沟丰富的红色资源，刘公抗俄碑、警钟广场、秀义广场等景点构成一道亮丽的红色风景线。吉林渤航旅游有限公司开发的&ldquo;别有洞天&rdquo;红色旅游项目总投资<span lang="EN-US">2.8</span>亿，是我县报送通化市<span lang="EN-US">33</span>个超<span lang="EN-US">5000</span>万元重点项目之一，是我县红色旅游重点项目之一，更是我县红色旅游的龙头项目，目前已经列入杨靖宇干部学院现场教学计划。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">2</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">、特色水果种植产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">五道沟镇利用自身地理位置及资源优势，因地制宜不断扩大果蔬种植规模。现有草莓种植园<span lang="EN-US">2.35</span>亩，李子种植果园<span lang="EN-US">40</span>亩、苹果园<span lang="EN-US">30</span>亩，蓝莓种植园<span lang="EN-US">120</span>亩。在建项目大青沟村温室大棚项目，<span lang="EN-US">2021</span>年后投产达效后草莓种植基地面积将提升至<span lang="EN-US">63</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">中药材种植产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">全镇种植五味子、人参、龙胆草等药材<span lang="EN-US">2000</span>余亩，覆盖<span lang="EN-US">11</span>个行政村。成立柳河县亿隆中草药种植专业合作社发展贝母种植<span lang="EN-US">58</span>亩，成立柳河县景友中草药种植种植专业合作社发展贝母种植<span lang="EN-US">15</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">畜牧养殖</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">五道沟镇现有规模化生猪养殖场<span lang="EN-US">13</span>家，规模化以下养殖场<span lang="EN-US">86</span>户，规模化肉鸡养殖场<span lang="EN-US">2</span>户，自有肉牛养殖户<span lang="EN-US">494</span>户。生猪存栏数<span lang="EN-US">14141</span>头，肉牛存栏数<span lang="EN-US">2019</span>头，肉鸡存栏量<span lang="EN-US">60000</span>套。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">5</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">、建材制造业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">柳河县启城水泥制品有限公司投资<span lang="EN-US">600</span>万元建设市政工程预制井生产线和新型模具项目，其中预制井生产线投资<span lang="EN-US">200</span>万元已正式投产，新型模具项目投资<span lang="EN-US">400</span>万元，将于<span lang="EN-US">8</span>月份投产达效。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">五道沟在县委县政府的坚强领导下，集合发展实际，提出&ldquo;四线四带一中心&rdquo;发展规划，全面加快乡村振兴建设步伐，推动全镇经济实现跨越式发展。即：依托五柳线打造&ldquo;红色旅游带&rdquo;；依托通梅一级公路沿线打造&ldquo;工业产业带&rdquo;；依托菜四线打造&ldquo;农业产业带&rdquo;；依托五福线打造&ldquo;宜居产业带&rdquo;。以镇区建设为中心，重点打造行政商贸中心。</span></p>
<p>&nbsp;</p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
