//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">向阳镇</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">向阳镇位于柳河县偏西南，地处两省四县交汇处。（西通辽宁新宾县、北接辽宁清源县、南临通化县）地理位置十分优越，是一统河发源地全镇幅员面积<span lang="EN-US">314</span>平方公里，耕地面积<span lang="EN-US">76720.14</span>亩。全镇共有<span lang="EN-US">13</span>个行政村，<span lang="EN-US">31</span>个自然屯。全镇共计<span lang="EN-US">4009</span>户，总人口为<span lang="EN-US">15041</span>人。农业总产值<span lang="EN-US">2.45</span>亿元，人均收入到<span lang="EN-US">1.1</span>万元。向阳镇是一统河的发源地，境内干支流总长<span lang="EN-US">80</span>多公里，地形以山地、丘陵为主，地势自西南向东北倾斜，农耕区主要分布于山间河谷平原上。矿产资源比较丰富，已开发的金厂沟金矿、西岗子铁矿、大兴铁矿等储量较大，未开发的池大地村钾长石矿的品位较高，储存量也比较丰富。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">向阳镇拥有优质玉米种植面积<span lang="EN-US">59253.78</span>亩，优质水稻面积<span lang="EN-US">11742.38</span>亩，优质大豆面积<span lang="EN-US">5723.98</span>亩。全镇苗木种植<span lang="EN-US">1400</span>余亩，其中绿化苗木<span lang="EN-US">180</span>亩。黑木耳发展到<span lang="EN-US">30</span>万袋，烤烟<span lang="EN-US">500</span>亩，葡萄<span lang="EN-US">200</span>亩；雪苹果<span lang="EN-US">3500</span>余亩，大榛子<span lang="EN-US">3000</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">全镇林业用地面积<span lang="EN-US">12846</span>公顷，有林地面积达<span lang="EN-US">9535</span>公顷，活立木总储备量达<span lang="EN-US">44</span>万立方米，森林覆盖率为<span lang="EN-US">42.9%</span>。林下参、人参、细辛、五味子、大黄、贝母等中草药材种植面积达到<span lang="EN-US">9800</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">全镇共有水域面积<span lang="EN-US">480</span>公顷，拥有小Ⅰ型水库<span lang="EN-US">2</span>座，小Ⅱ型水库<span lang="EN-US">6</span>座，塘坝<span lang="EN-US">13</span>座，拦河闸坝<span lang="EN-US">16</span>座，水域面积<span lang="EN-US">9033.6</span>亩，其中：流河面积<span lang="EN-US">46.9</span>亩，水库面积<span lang="EN-US">1015</span>亩，其它坑塘、苇地滩涂、沟渠面积为<span lang="EN-US">7971.7</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">积极解决大兴铁矿复工复产过程中的难题，促使企业早日恢复生产，预计<span lang="EN-US">8</span>月份投产，钰坤金矿现已探明黄金储量<span lang="EN-US">1.67</span>吨，项目建设总投资<span lang="EN-US">6</span>亿元，年加工金矿石<span lang="EN-US">15</span>万吨，年产金精粉<span lang="EN-US">7000</span>吨，年可实现产值<span lang="EN-US">1.4</span>亿元，解决社会就业<span lang="EN-US">400</span>人。向阳铁矿探矿<span lang="EN-US">3.23</span>平方公里，现已完成投资<span lang="EN-US">3</span>亿元，新增锤破、强磁、球磨和轭破生产设备，年加工铁矿石能力由原来的<span lang="EN-US">400</span>万吨提高到<span lang="EN-US">600</span>万吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">野山参产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">吉林云岭野山参科技开发有限公司坐落在吉林省柳河县向阳镇，<span lang="EN-US">2016</span>年由吉林云岭野山参科技开发有限公司投资建设，计划总投资<span lang="EN-US">5</span>亿元，现已完成投资<span lang="EN-US">2.2</span>亿元，占地面积<span lang="EN-US">9800</span>亩，建筑面积<span lang="EN-US">3500</span>平方米，有林下野山参<span lang="EN-US">7300</span>亩，<span lang="EN-US">2</span>亿棵左右，是一家集云岭野山参发展保护、产品研发和旅游服务为一体的新型企业，公司投资<span lang="EN-US">2</span>亿元用于野山参产品研发，生态保护和旅游服务设施建设，均已形成规模，成为生态发展的示范区，云岭野山参保护区山高林密、溪水清澈、气候宜人、地理位置独特、优美的自然风光，和优越的地理环境形成了天然、生态、古迹大融合的<span lang="EN-US">AAA</span>级景区，保护区内星级宾馆、地下酒窖、人参博物馆、多功能会议厅、垂钓、网球场等娱乐休闲项目，设施完备功能齐全。野山参采挖、野玫瑰观赏、冷冷水鱼垂钓、野生山菜、菌类、果实采摘更是别有风趣，这里绝对是观光旅游，休闲度假的绝好去处。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">特色农业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">推进西岗子生态村建设项目，该项目<span lang="EN-US">2021</span>年计划投资<span lang="EN-US">7500</span>万元，主要建设大规模黑牛养殖基地及<span lang="EN-US">2000</span>亩水果黏玉米种植，全面完成<span lang="EN-US">37</span>户民宿改造任务。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">畜牧养殖业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">向阳镇在畜牧业生产方面全面实施&ldquo;粮变肉&rdquo;工程，全镇养猪专业户<span lang="EN-US">16</span>户，养猪<span lang="EN-US">2600</span>头。全镇有黄牛养殖专业户<span lang="EN-US">18</span>户，养牛<span lang="EN-US">1500</span>头。肉鸡养殖<span lang="EN-US">13</span>户，年出栏肉鸡<span lang="EN-US">700</span>只、全镇养羊<span lang="EN-US">3500</span>只、水产及林蛙养殖面积达到<span lang="EN-US">150</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;"><strong>四、未来发展方向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体;">改善周边农村农业生产模式，从大的方面来说﹐就是建立区域农业生态系统，以村为基本单位，将各个村连起来<span lang="EN-US">,</span>每一个村在这个生态系统里都扮演着不同级别的角色，可以根据当地的优越地理形势，发展其适宜的农产品，而有的地方不适宜发展农业或其他的一些原因，可以将其设置为农副产品加工及深加工基地，各个村之间依托其有利地形及特色，向着城市化发展。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
