//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">中岗街道</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">中岗街道办事处于<span lang="EN-US">2019</span>年<span lang="EN-US">3</span>月成立，管辖范围为东起裕民路、朝阳路沿振兴大街至太平村与柳树村村界，西至和兴路、英利路及城南村与东方红村、联合村村界，南起城南村、太平村与大郑家村、联合村村界，北至北山。街道下辖<span lang="EN-US">3</span>个社区，<span lang="EN-US">3</span>个村，总面积<span lang="EN-US">26.45</span>平方公里。街道总户数<span lang="EN-US">14752</span>户，<span lang="EN-US">34715</span>人。其中，村民<span lang="EN-US">1242</span>户，人口<span lang="EN-US">4050</span>人；社区居民<span lang="EN-US">13510</span>户，人口<span lang="EN-US">30665</span>人。耕地共计<span lang="EN-US">3587.3</span>亩。其中旱田地<span lang="EN-US">2558.3</span>亩、水田地总数<span lang="EN-US">1029</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、资源情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">旅游资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">中岗街道旅游资源比较突出。城区内世纪广场、湿地公园并连着南山公园，每逢节假休息日城区巨大大量的人流量汇聚于此。城区边生态旅游山庄也凭借得天独厚的位置环境颇有影响力，享有较好口碑。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇农业资源丰富，种植业基础牢固。<span lang="EN-US">2020</span>年粮食作物总产量<span lang="EN-US">65878</span>吨，其中稻谷产量<span lang="EN-US">7468</span>吨、玉米产量<span lang="EN-US">58410</span>吨。现有农业合作社<span lang="EN-US">136</span>个。镇内有国家级水稻种植标准化种植基地、国家级山葡萄示范区、省级农产品加工示范区等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">林业资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇林业资源分布广泛，大郑家、柳树两村林地面积占比较大。全镇林地总面积<span lang="EN-US">19538.14</span>亩，其中天然林<span lang="EN-US">4407.8</span>亩、人工林<span lang="EN-US">3982.2</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水利资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇水资源充沛，河流众多，水利设施齐全。域内主要分为一统河、碱水河两大流域，共有河流<span lang="EN-US">55</span>条，全长<span lang="EN-US">230</span>公里，其中流域面积<span lang="EN-US">20</span>平方公里以上河流<span lang="EN-US">5</span>条，一级支流<span lang="EN-US">18</span>条，二级支流<span lang="EN-US">14</span>条。有小（一）型水库<span lang="EN-US">2</span>座、小（二）型水库<span lang="EN-US">8</span>座，塘坝<span lang="EN-US">20</span>座、拦河坝<span lang="EN-US">3</span>座、拦河闸<span lang="EN-US">20</span>处、电灌站<span lang="EN-US">2</span>座。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">5.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">矿产资源</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇有矿产用地<span lang="EN-US">900.31</span>亩，铁矿、石灰矿、石矿等资源储量较大，开发利用价值较高。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、产业情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色水果产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇水果种植总面积<span lang="EN-US">8500</span>余亩，其中苹果梨面积<span lang="EN-US">6000</span>余亩，分布在白家村、砬门村和复兴村，白家村一村种植面积就达<span lang="EN-US">3500</span>亩，产量达<span lang="EN-US">2000</span>吨，销售收入达<span lang="EN-US">410</span>余万元，直接带动<span lang="EN-US">120</span>余户村民实现增收。<span lang="EN-US">2017</span>年，由电子商务办公室牵头，着力打造&ldquo;白家、砬门苹果梨&rdquo;特色品牌，申办无公害绿色食品认证。此外，三仙夹吉胜李子等特色水果，远近闻名。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色棚膜果蔬产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇现有大棚<span lang="EN-US">150</span>栋，主要发展蔬菜和水果种植产业。近年来镇政府不断加大政策扶持力度，培育出一批优秀专业种植合作社。其中，以里仁村吉柳金彭种植专业合作社为主要代表，合作社投资<span lang="EN-US">350</span>万元，<span lang="EN-US">2016</span>年建设占地面积<span lang="EN-US">90</span>亩的果蔬种植采摘园区，现有日光温室<span lang="EN-US">12</span>栋、冷棚<span lang="EN-US">30</span>栋，用于栽种草莓、蔬菜等。<span lang="EN-US">2020</span>年每栋草莓大棚收入<span lang="EN-US">13</span>万元以上，利润达<span lang="EN-US">10</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特色中草药材产业</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇中草药材种植面积达<span lang="EN-US">2300</span>余亩，集中分布在复兴村、柳树村、里仁村和复新村，主要种植苍术、赤芍、细辛等品种。近年来镇政府不断加大对茂丰中草药材种植专业合作社培育扶持力度，以打造中医药材标准化种植基地为目标，连片规划栽种苍术、黄精、白鲜皮等中小药材，现已发展成为我县规模较大、起步较早、种类较多的中药材种植及种苗繁育基地。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">4.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">畜牧养殖</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇现有牧业小区<span lang="EN-US">5</span>个。家畜家禽存栏量<span lang="EN-US">60</span>余万头（只），其中，猪<span lang="EN-US">7166</span>头、牛<span lang="EN-US">1863</span>头、羊<span lang="EN-US">1087</span>只、鸡鸭鹅<span lang="EN-US">56</span>万只。特种养殖产业主要以饲养梅花鹿为主，现有鹿场<span lang="EN-US">2</span>个，其中天强鹿场<span lang="EN-US">120</span>头、大郑家鹿场<span lang="EN-US">80</span>头。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">5.</span><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特种种植</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河镇特种种植产业分布广泛，种类众多。特种种植面积<span lang="EN-US">13700</span>余亩，其中烤烟为传统产业，现有<span lang="EN-US">1257</span>亩；果树类主要种植苹果梨、苹果、李子、蓝莓等作物，共<span lang="EN-US">6807</span>亩；中草药材以苍术、白芍、赤芍、五味子等为主，共<span lang="EN-US">2357</span>亩；棚膜经济主要以种植蔬菜、草莓为主，共<span lang="EN-US">921</span>亩；葡萄种植分为生食和酿酒原料两类，共<span lang="EN-US">1710</span>亩；大榛子<span lang="EN-US">727</span>亩。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 16.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">依托环绕县城地理优势，以农产品深加工为发展主线，畜牧养殖观光旅游、矿产开发利用和生产加工型企业为发展着力点，使镇域经济再上上新台阶。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
