//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">教育设施</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">截止到<span lang="EN-US">2020</span>年，柳河县共有幼儿园<span lang="EN-US">82</span>所。各级各类学校<span lang="EN-US">43</span>所，其中独立小学<span lang="EN-US">11</span>所，一贯制学校<span lang="EN-US">13</span>所，独立初中<span lang="EN-US">8</span>所，高中<span lang="EN-US">3</span>所，育智学校<span lang="EN-US">1</span>所，村小及教学点<span lang="EN-US">7</span>所。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县共有在校学生<span lang="EN-US">28894</span>人，其中幼儿<span lang="EN-US">6771</span>人，小学<span lang="EN-US">15073</span>人，初中<span lang="EN-US">7958</span>人，高中<span lang="EN-US">5863</span>人。全县在编教师<span lang="EN-US">2893</span>人。全县教育系统共有<span lang="EN-US">12</span>个党总支，<span lang="EN-US">55</span>个党支部，党员<span lang="EN-US">1619</span>名。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2015</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年，柳河县实现了义务教育&ldquo;基本均衡&rdquo;目标，顺利通过吉林省人民政府教育督导室检查验收。<span lang="EN-US">2016</span>年&mdash;<span lang="EN-US">2020</span>年，全县累计投资<span lang="EN-US">4.3</span>亿元，完成了教育基础设施新建及维修改造项目<span lang="EN-US">108</span>个，新建校舍<span lang="EN-US">7.1</span>万平方米，维修改造校舍<span lang="EN-US">17</span>万平方米，改造操场<span lang="EN-US">21</span>万平方米，极大推进了县域各类教育共同发展。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县实验幼儿园</strong>成立于<span lang="EN-US">1958</span>年，是柳河县内唯一所省级示范幼儿园。幼儿园占地面积<span lang="EN-US">15500</span>平方米，建筑面积<span lang="EN-US">4189</span>平方米，户外场地<span lang="EN-US">9300</span>余平方米，绿地面积<span lang="EN-US">5500</span>余平。现有教职工<span lang="EN-US">76</span>人，开设<span lang="EN-US">16</span>个教学班级，可容纳<span lang="EN-US">480</span>名幼儿。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县长青小学</strong>成立于<span lang="EN-US">1986</span>年，学校占地面积<span lang="EN-US">12568</span>平方米。校舍建筑面积<span lang="EN-US">8766</span>平方米，现有教职工<span lang="EN-US">93</span>人开设<span lang="EN-US">40</span>个教学班，在校生<span lang="EN-US">2010</span>人；开设<span lang="EN-US">7</span>个学前班，学前幼儿<span lang="EN-US">348</span>人。学校先后获被评为&ldquo;全国冰雪特色学校&rdquo;、&ldquo;吉林省美育特色学校&rdquo;、&ldquo;吉林省生命与安全教育先进学校&rdquo;。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县实验小学</strong>成立于<span lang="EN-US">1958</span>年，学校占地面积<span lang="EN-US">18836</span>平方米，校舍面积<span lang="EN-US">18335</span>平方米。现有教师<span lang="EN-US">173</span>人，开设<span lang="EN-US">60</span>个教学班、<span lang="EN-US">11</span>个幼儿班，在校学生<span lang="EN-US">2840</span>人，学前幼儿<span lang="EN-US">470</span>人。学校先后被评为&ldquo;全国兰亭小学&rdquo;、&ldquo;全国特色教育先进单位&rdquo;、&ldquo;全国艺术教育先进单位&rdquo;</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县第九中学</strong>成立于<span lang="EN-US">1979</span>年，是一所基础教育和学校教育教学为主的初级中学。学校占地<span lang="EN-US">14985</span>平方米，建筑面积<span lang="EN-US">11910</span>平方米，现有专任教师<span lang="EN-US">127</span>人，可容纳学生<span lang="EN-US">1700</span>余人。学校被授予<span lang="EN-US">2020</span>年通化市教育管理服务工作先进集体、国培计划优秀学校管理团队、<span lang="EN-US">2019</span>年荣获柳河县中小学优秀干训实践基地校等荣誉。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县第十中学</strong>成立<span lang="EN-US">1991</span>年，是一所基础教育和学校教育教学为主的初级中学。学校占地<span lang="EN-US">27200</span>平方米，建筑面积<span lang="EN-US">11168</span>平方米，现有在岗教职工<span lang="EN-US">137</span>人，<span lang="EN-US">34</span>个教学班，可容纳学生<span lang="EN-US">2000</span>人。学校先后被评为国家级&ldquo;传统美德教育实验校、心理健康教育实验校、外语教育实验校、青少年体育俱乐部&rdquo;，省级&ldquo;绿色校园、电化教育示范校、优秀家长学校、百姓口碑金奖单位、百佳全面发展校&rdquo;，市级&ldquo;五星级文明单位&rdquo;，县级&ldquo;养成教育示范校&rdquo;等诸多殊荣。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县第八中学</strong>成立于<span lang="EN-US">1976</span>年，是一所公办普通高中。校园占地面积<span lang="EN-US">92868</span>平方米<span lang="EN-US">,</span>总建筑面积<span lang="EN-US">28577</span>平方米，现有教职员工<span lang="EN-US">131</span>人，设有教学班<span lang="EN-US">33</span>个，在校生<span lang="EN-US">1800</span>余人。学校先后被评为&ldquo;吉林省生命与安全教育先进单位&rdquo;&ldquo;百佳科研典范校&rdquo;。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县第一中学</strong>成立于<span lang="EN-US">1947</span>年，是吉林省重点中学。学校占地面积<span lang="EN-US">140</span>亩，建筑面积<span lang="EN-US">3.8</span>万平方米，学校现有<span lang="EN-US">48</span>个教学班，在校学生<span lang="EN-US">2585</span>人，教职工共<span lang="EN-US">197</span>人。<span lang="EN-US">80</span>年代以来，学校先后有<span lang="EN-US">52</span>名毕业生考入<span lang="EN-US"><a href="https://baike.baidu.com/item/%E6%B8%85%E5%8D%8E/1832793" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E5%8E%BF%E7%AC%AC%E4%B8%80%E4%B8%AD%E5%AD%A6/_blank"><span lang="EN-US"><span lang="EN-US">清华</span></span></a></span>、北大和<span lang="EN-US"><a href="https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E5%8E%BF%E7%AC%AC%E4%B8%80%E4%B8%AD%E5%AD%A6/_blank"><span lang="EN-US"><span lang="EN-US">中国科技大学</span></span></a></span>。<span lang="EN-US">2021</span>年高考成绩有新突破，个人总分位居通化地区首位。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>柳河县职业教育中心</strong>成立于<span lang="EN-US">1982</span>年，为公办职业技术学校。学校占地面积为<span lang="EN-US">74515</span>平方米，建筑面积为<span lang="EN-US">24738.35</span>平方米，学校现有教职工<span lang="EN-US">131</span>人，可容纳在校就读学生<span lang="EN-US">2000</span>人左右。学校开设了计算机应用、财务会计、机械电子、<span lang="EN-US"><a href="https://baike.baidu.com/item/%E6%9C%8D%E8%A3%85%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%B7%A5%E7%A8%8B/3739687" target="https://baike.baidu.com/item/_blank"><span lang="EN-US"><span lang="EN-US">服<span lang="EN-US">装设计与工程</span></span></span></a></span>、广告艺术设计、文秘、种植、养殖、汽车电器维修、机械加工、幼师、电工等<span lang="EN-US">14</span>个专业。学校近年先后获得&ldquo;吉林省改革创新实验校称号&rdquo;、&ldquo;学校管理服务先进集体&rdquo;&ldquo;<span lang="EN-US">2019</span>、<span lang="EN-US">2020</span>和<span lang="EN-US">2021</span>年度学校管理优秀单位&rdquo;等省、市、县级荣誉称号。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
