//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">医疗设施</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、整体情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">目前，全县共有医疗卫生机构<span lang="EN-US">382</span>所。其中，公立医疗卫生机构<span lang="EN-US">22</span>所，村卫生室<span lang="EN-US">203</span>个，村个体卫生所<span lang="EN-US">60</span>个，厂矿卫生所<span lang="EN-US">2</span>所，全县民营医院<span lang="EN-US">1</span>所，个体诊所<span lang="EN-US">93</span>所。全县共有医疗卫生人员<span lang="EN-US">1921</span>人。其中，执业（助理）医师<span lang="EN-US">589</span>人，注册护士<span lang="EN-US">428</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、医疗保障情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县基本医疗保险经办工作通过在县政务服务中心设置服务窗口，实现基本医保、大病保险、医疗救助<span lang="EN-US">&ldquo;</span>一站式服务、一窗口办理、一单制结算<span lang="EN-US">&rdquo;</span>。通过实施基本医保、大病保险、医疗救助三重制度综合保障，城镇职工和城乡居民医保县域内住院患者报销比例分别达到<span lang="EN-US">75%</span>和<span lang="EN-US">70%</span>。<span lang="EN-US"><span style="mso-spacerun: yes;">&nbsp;&nbsp; </span></span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">三、县域主要医疗机构简介（卫健局提供）</span></strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）柳河县中心医院</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县中心医院院区面积<span lang="EN-US">61320.81</span>平方米<span lang="EN-US">, </span>设有<span lang="EN-US">20</span>个临床专科，<span lang="EN-US">6</span>个辅助检查科室，编制床位<span lang="EN-US">308</span>张，现有职工<span lang="EN-US">307</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）柳河县人民医院</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县人民医院建筑面积<span lang="EN-US">3.7</span>万平方米<span lang="EN-US">, </span>设有<span lang="EN-US">28</span>个临床专科，<span lang="EN-US">7</span>个辅助检查科室，编制床位<span lang="EN-US">600</span>张，现有在岗职工<span lang="EN-US">605</span>人。<span lang="EN-US">&nbsp;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）柳河县中医医院</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县中医医院占地面积<span lang="EN-US">16000</span>平方米，建筑面积<span lang="EN-US">12000</span>平方米，开放床位<span lang="EN-US">200</span>张，在岗职工<span lang="EN-US">239</span>人。全年门诊接诊<span lang="EN-US">51484</span>人次，住院<span lang="EN-US">3874</span>人次，手术<span lang="EN-US">670</span>人次。总资产规模约<span lang="EN-US">5600</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（四）妇幼保健院</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">妇幼保健院占地面积<span lang="EN-US">****</span>，建筑面积<span lang="EN-US">5524.34</span>平方米，编制床位<span lang="EN-US">60</span>张，全院在岗职工<span lang="EN-US">48</span>人。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（五）疾病预防控制中心</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">疾病预防控制中心占地面积<span lang="EN-US">2589</span>平方米，建筑面积<span lang="EN-US">3370</span>平方米，业务用房<span lang="EN-US">3000</span>平方米。在岗职工<span lang="EN-US">42</span>人。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
