//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">水、电和煤气供应</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、自来水供应和价格</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）城镇供水能力</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2021</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年柳河镇区内日供水能力约为<span lang="EN-US">5</span>万吨，主要水源为安口镇烧锅水库及安口水库。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）自来水收费价格</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">居民用水</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">第一阶梯：居民用水量<span lang="EN-US">15</span>吨<span lang="EN-US">/</span>户<span lang="EN-US">/</span>月以下（含<span lang="EN-US">15</span>吨），到户价格<span lang="EN-US">4.25</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">(</span>含污水处理费<span lang="EN-US">0.85</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">)</span>；</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">第二阶梯：居民用水量<span lang="EN-US">16-20</span>吨<span lang="EN-US">/</span>户<span lang="EN-US">/</span>月以下（含<span lang="EN-US">20</span>吨），到户价格<span lang="EN-US">5.95</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">(</span>含污水处理费<span lang="EN-US">0.85</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">)</span>；</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">第三阶梯：居民用水量<span lang="EN-US">21</span>吨<span lang="EN-US">/</span>户<span lang="EN-US">/</span>月以上<span lang="EN-US">,</span>到户价格<span lang="EN-US">7.65</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">(</span>含污水处理费<span lang="EN-US">0.85</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">)</span>。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">工业用水</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">机关企事业水价：<span lang="EN-US">6.50</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">(</span>含污水处理费<span lang="EN-US">2</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">)</span>；</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">3.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特业用水</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">特种行业水价：<span lang="EN-US">10.5</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">(</span>含污水处理费<span lang="EN-US">2.5</span>元<span lang="EN-US">/</span>吨<span lang="EN-US">)</span>。每户基本人口为<span lang="EN-US">4</span>人及以下，超过<span lang="EN-US">4</span>人的居民用水户，每增加<span lang="EN-US">1</span>人<span lang="EN-US">,</span>月增加用水量<span lang="EN-US">3</span>吨。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、电力供应和价格</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）电力供应能力</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">1.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">城网供电能力</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县现拥有<span lang="EN-US">220</span>千伏一次变电站<span lang="EN-US">1</span>座，主变<span lang="EN-US">1</span>台容量<span lang="EN-US">90000</span>千伏安；拥有<span lang="EN-US">66</span>千伏二次变电站<span lang="EN-US">3</span>座，主变<span lang="EN-US">8</span>台总容量<span lang="EN-US">131500</span>千伏安。现有<span lang="EN-US">10</span>千伏有损公配线路<span lang="EN-US">15</span>条，线路供电范围覆盖整个县城及三源浦镇，电力供应能力充足可靠，完全能够满足未来<span lang="EN-US">5</span>年用电负荷发展要求。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2.</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">农网供电能力</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">目前全县农电拥有清泉、六道、圣水等<span lang="EN-US">11</span>个变电所，主变总容量为<span lang="EN-US">93850</span>千伏安，电力供应能力充足。</span></p>`,
		text2: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）售电价格</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">电网售电价格表</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">单位：元／千瓦时</span></p>`,
		text3: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、天然气供应和价格</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县城设计供应能力约为<span lang="EN-US">5</span>万户，现已安装近<span lang="EN-US">4</span>万户，累计供气户数约<span lang="EN-US">3.6</span>万户，价格为<span lang="EN-US">4.5</span>元<span lang="EN-US">/</span>立方米。液化气贮存能力为<span lang="EN-US">1000</span>吨，价格为<span lang="EN-US">8</span>元<span lang="EN-US">/</span>公斤。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、县城供暖和价格</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）供暖面积及设施</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县城区拥有供热站<span lang="EN-US">2</span>座，其中：蓝天供热站，供热面积<span lang="EN-US">620.2</span>万平方米，建筑面积<span lang="EN-US">18246.14</span>平方米，厂区面积<span lang="EN-US">52784</span>平方米，<span lang="EN-US">90</span>吨供热机组<span lang="EN-US">4</span>座（另有<span lang="EN-US">3</span>台<span lang="EN-US">40</span>吨备用炉）；红日供热站，供热面积<span lang="EN-US">32</span>万平方米，建筑面积<span lang="EN-US">1390</span>平方米，厂区面积<span lang="EN-US">2580</span>平方米，<span lang="EN-US">30</span>吨供热机组<span lang="EN-US">1</span>座。城区入网供应热面积约<span lang="EN-US">652.2</span>万平方米，平均每年实际供热面积约<span lang="EN-US">447</span>万平方米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）供暖价格</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">住宅：<span lang="EN-US">28</span>元<span lang="EN-US">/</span>平方米；商业、机关及其他事业单位：<span lang="EN-US">35</span>元<span lang="EN-US">/</span>平方米；学校、医院、公益事业单位：<span lang="EN-US">30</span>元年<span lang="EN-US">/</span>平方米；普通限高<span lang="EN-US">3</span>米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>五、项目审批收费标准</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）人防异地建设费</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在我县城规划区、开发区内新建项目的人防设施，本着应建必建原则，如有特殊情况无法建设人防设施，按配建面积需缴纳每平方米<span lang="EN-US">1072</span>元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）市政基础设施配套费</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在我县城规划区、开发区内新建项目及扩建的新增面积部分或原属于减免配套费的建设项目改变用途的，均按建筑面积每平方米收取<span lang="EN-US">18.05</span>元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）城市消防基础设施配套费</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">在我县城规划区、开发区内新建项目，建筑面积民宅每平方米收取<span lang="EN-US">0.9025</span>元，其他建筑每平方米收取<span lang="EN-US">1.805</span>元。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
