//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">交通运输</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">一、公路基本情况</span></strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">全县境内公路总里程为<span lang="EN-US">1462.7</span>公里（不含<span lang="EN-US">326</span>条<span lang="EN-US">847.883</span>公里屯道和巷道），其中：</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">通车高速<span lang="EN-US">3</span>条<span lang="EN-US">92.6</span>公里，即：通梅高速<span lang="EN-US">51.9</span>公里，鹤大高速<span lang="EN-US">8.2</span>公里，辉白高速<span lang="EN-US">32.5</span>公里<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">国道<span lang="EN-US">1</span>条<span lang="EN-US">66.1</span>公里，即：<span lang="EN-US">G303</span>集锡线<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">省道<span lang="EN-US">2</span>条<span lang="EN-US">150.1</span>公里，即：<span lang="EN-US">S206</span>永新线<span lang="EN-US">105.655</span>公里，<span lang="EN-US">S207</span>辉三线<span lang="EN-US">44.509</span>公里<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">县道<span lang="EN-US">7</span>条<span lang="EN-US">239.6</span>公里，即：快朝线<span lang="EN-US">59.283</span>公里，柳西线<span lang="EN-US">11.336</span>公里，凉靖线<span lang="EN-US">14.003</span>公里，驼姜线<span lang="EN-US">24.476</span>公里，五柳线<span lang="EN-US">35.53</span>公里，大罗线<span lang="EN-US">17.577</span>公里，安回线<span lang="EN-US">77.413</span>公里<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">乡道<span lang="EN-US">123</span>条<span lang="EN-US">626.203</span>公里<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">村道<span lang="EN-US">210</span>条<span lang="EN-US">280.9</span>公里<span lang="EN-US">;</span></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">桥梁<span lang="EN-US">352</span>座，其中：大桥<span lang="EN-US">7</span>座、中桥<span lang="EN-US">69</span>座、小桥<span lang="EN-US">276</span>座。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">二、公共交通基本情况</span></strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">全县<span lang="EN-US">219</span>个行政村全部通硬化路和客运车辆；<span lang="EN-US">512</span>个自然屯中有<span lang="EN-US">507</span>个通硬化路，占总数的<span lang="EN-US">99%</span>；城区有<span lang="EN-US">6</span>条公交线路，<span lang="EN-US">87</span>台公交车（其中新能源公交车<span lang="EN-US">61</span>台）；共有公路营运线路<span lang="EN-US">89</span>条，车辆<span lang="EN-US">159</span>台，日营运里程<span lang="EN-US">4.5</span>万公里、发车<span lang="EN-US">408</span>个班次、输送旅客<span lang="EN-US">8000</span>多人次；出租车<span lang="EN-US">653</span>台；货车<span lang="EN-US">1830</span>台，年货运量<span lang="EN-US">383</span>万吨。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">三、铁路基本情况（火车站）</span></strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">柳河站位于中国吉林省<span lang="EN-US"><a href="https://baike.baidu.com/item/%E9%80%9A%E5%8C%96%E5%B8%82/1485704" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E7%AB%99/_blank"><span lang="EN-US"><span lang="EN-US">通化市</span></span></a></span>梅集铁路柳河镇区域，始建于<span lang="EN-US">1937</span>年，是<span lang="EN-US"><a href="https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E9%93%81%E8%B7%AF%E6%B2%88%E9%98%B3%E5%B1%80%E9%9B%86%E5%9B%A2%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/22204833" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E7%AB%99/_blank"><span lang="EN-US"><span lang="EN-US">中国铁路沈阳局集团有限公司</span></span></a></span>管辖的三等站，距<span lang="EN-US"><a href="https://baike.baidu.com/item/%E6%A2%85%E6%B2%B3%E5%8F%A3%E7%AB%99/7905404" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E7%AB%99/_blank"><span lang="EN-US"><span lang="EN-US">梅河口站</span></span></a>32.4</span>公里，距<span lang="EN-US"><a href="https://baike.baidu.com/item/%E9%9B%86%E5%AE%89%E7%AB%99/9487012" target="https://baike.baidu.com/item/%E6%9F%B3%E6%B2%B3%E7%AB%99/_blank"><span lang="EN-US"><span lang="EN-US">集安站</span></span></a>211.7</span>公里。柳河站有直达北京、青岛、大连、沈阳、长春、吉林、龙井、白山、通化等城市的<span lang="EN-US">13</span>班次列车，站内旅客客流量约<span lang="EN-US">10</span>万人次。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">柳河站按技术性质为中间站，按业务性质为客货运站，站内建有两台三线。站内拥有两条货物线，营运限制为：不办理零担及危险货物，起重能力<span lang="EN-US">40</span>吨，集装箱可运载<span lang="EN-US">20</span>英尺箱、<span lang="EN-US">40</span>英尺箱、<span lang="EN-US">35</span>吨箱（发到）、千散箱、敞顶箱。近年来，站内办理货物运输主要特点和发到货物品类以：袋装粮食、散装玉米为主，同时还有非金属矿石、化肥等其他散装运输货物，年货运吞吐量平均约为<span lang="EN-US">9</span>至<span lang="EN-US">12</span>万吨。</span></p>`,
		text2: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">四、货运价格标准（发改物价）</span></strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><strong> </strong></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;"><strong>五、航空运输基本情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">（一）机场简介</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">通化机场位于柳河县三源浦镇西南方向，与通化市区公路距离<span lang="EN-US">47</span>公里，与柳河县城公路距离<span lang="EN-US">25.1</span>公里。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">机场于<span lang="EN-US">2011</span>年<span lang="EN-US">6</span>月<span lang="EN-US">19</span>日正式开工建设，<span lang="EN-US">2014</span>年<span lang="EN-US">6</span>月<span lang="EN-US">18</span>日正式通航。机场航站楼面积<span lang="EN-US">3034</span>平方米，民航站坪设<span lang="EN-US">4</span>个机位，其中<span lang="EN-US">3</span>个<span lang="EN-US">C</span>类机位，<span lang="EN-US">1</span>个<span lang="EN-US">B</span>类机位；跑道长<span lang="EN-US">2300</span>米，宽<span lang="EN-US">45</span>米；供起降空中客车<span lang="EN-US">A320</span>、波音<span lang="EN-US">737</span>等双发中程窄体客机及其以下机型，可满足年旅客吞吐量<span lang="EN-US">19.4</span>万人次、货邮吞吐量<span lang="EN-US">970</span>吨、飞机起降<span lang="EN-US">2338</span>架次的使用需求。通化机场是省内第三个运营支线运输机场。在吉林省&ldquo;一主、六双&rdquo;总体布局中，通化属于属于&ldquo;双廊、双带、双线&rdquo;核心区之一：医药健康产业走廊，沿图们江鸭绿江开发开放经济带、鸭绿江边境风情旅游线。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">开航至今，航班量和旅客吞吐量年均增长率达<span lang="EN-US">10%</span>以上。<span lang="EN-US">2020</span>年运输航班量为<span lang="EN-US">1324</span>架次，旅客吞吐量<span lang="EN-US">9.88</span>万人次。目前，通化机场运营<span lang="EN-US">5</span>条航线、通航九个城市，分别为北京、上海、广州、天津、大连、杭州、台州、重庆、哈尔滨。开航以来共保证航班起降<span lang="EN-US">4000</span>余架次，完成旅客吞吐量近<span lang="EN-US">38</span>万人次。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">（二）机场未来发展方向</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">十四五期间，机场将开展新航站楼、站坪及机位建设项目，新增部分与现有站坪相接，做到新旧站坪统一规划，共设置<span lang="EN-US">8</span>个<span lang="EN-US">C</span>类机位和<span lang="EN-US">2</span>个<span lang="EN-US">C</span>类除冰坪，其中包含<span lang="EN-US">5</span>个廊桥机位。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体;">机场近年将逐渐拓展航班直飞广州、厦门、海口（经停广州）等航线，全力发展直飞短途国际（韩国、日本等）和（香港、澳门等）航线。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
