//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">矿产资源</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;">&nbsp;</p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、矿产资源基础情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">目前，柳河县境内已发现各类矿产<span lang="EN-US">34</span>种，其中有查明资源储量矿产<span lang="EN-US">16</span>种，列入吉林省矿产资源储量数据库矿产<span lang="EN-US">14</span>种，已开发利用矿种<span lang="EN-US">11</span>种。能源矿产主要有煤炭，金属矿产主要有铁、金、银，非金属矿产主要有熔剂用灰岩、冶金用白云岩、冶金用石英岩、泥炭、石膏、水泥用灰岩、建筑石料用灰岩、饰面用灰岩、砖瓦用页岩、饰面用玄武岩、建筑用玄武岩、火山渣，资源储量十分丰富。优势矿种包括：铁、石膏、饰面用玄武岩、建筑用玄武岩、建筑石料用灰岩、硅藻土、火山渣等。铁矿矿区数为<span lang="EN-US">11</span>个，矿床规模以小型为主，主要分布在三源浦镇、孤山子镇、向阳镇等地。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、主要矿产资源储量</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">截止<span lang="EN-US">2020</span>年，全县有效探矿权数<span lang="EN-US">7</span>个，勘查区总面积<span lang="EN-US">27.31</span>平方公里，勘查阶段包括勘探、详查、普查，其中勘探项目<span lang="EN-US">3</span>个，详查项目<span lang="EN-US">4</span>个，<span lang="EN-US">2020</span>年度勘查总投入资金<span lang="EN-US">30</span>万元。主要投向铁矿<span lang="EN-US">3</span>个，金矿<span lang="EN-US">1</span>个，泥灰岩<span lang="EN-US">2</span>个，含钾岩石<span lang="EN-US">1</span>个等矿种勘查。各类矿产储量数据如下：</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）煤炭：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">1545.87</span>千吨，累计查明：<span lang="EN-US">3665.21</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）铁矿：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">46617.83</span>千吨，累计查明：<span lang="EN-US">49166.73</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）金矿（岩金）：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">4374.45</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">5187.53</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（四）金矿（砂金）：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">673.5</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">673.5</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（五）银矿<span lang="EN-US">:2020</span>年年末保有<span lang="EN-US">9.34</span>吨，累计查明：<span lang="EN-US">9.34</span>吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（六）熔剂用灰岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">72767.63</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">76293.33</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（七）冶金用白云岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">18353.76</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">18353.76</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（八）冶金用脉石英：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">95.67</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">108</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（九）泥炭：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">155.02</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">156</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十）石膏：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">3299.73</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">6069.91</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十一）水泥用灰岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">1140</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">1140</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十二）饰面用灰岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">1790</span>矿石<span lang="EN-US">/</span>千吨，累计查明：<span lang="EN-US">1790</span>矿石<span lang="EN-US">/</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十三）火山渣：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">3963.24</span>千吨，累计查明：<span lang="EN-US">4030.52</span>千吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十四）建筑石料用灰岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">4983.97</span>矿石<span lang="EN-US">/</span>千立方米，累计查明：<span lang="EN-US">10316.77</span>矿石<span lang="EN-US">/</span>千立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十五）砖瓦用页岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">167.26</span>矿石<span lang="EN-US">/</span>千立方米，累计查明：<span lang="EN-US">171.70</span>矿石<span lang="EN-US">/</span>千立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十六）饰面用玄武岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">1155.52</span>矿石<span lang="EN-US">/</span>千立方米，累计查明：<span lang="EN-US">1250.57</span>矿石<span lang="EN-US">/</span>千立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（十七）建筑用玄武岩：<span lang="EN-US">2020</span>年年末保有<span lang="EN-US">1659.85</span>矿石<span lang="EN-US">/</span>千立方米，累计查明：<span lang="EN-US">1881.01</span>矿石<span lang="EN-US">/</span>千立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、资源开发利用情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县现有铁矿企业<span lang="EN-US">11</span>户，金矿企业<span lang="EN-US">1</span>户，石膏矿企业<span lang="EN-US">4</span>户，火山渣矿企业<span lang="EN-US">1</span>户，主要生产免烧砖，建筑用石料矿山<span lang="EN-US">4</span>户，其他非金属矿企业<span lang="EN-US">8</span>户。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县铁矿企业未生产原因：由于市场价格因素，全国市场需求量减少，导致铁矿石价格低迷，企业生产积极性不高。近年铁矿石价格回暖，有些铁矿企业正积极复工复产。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">非金属矿山企业受房地产市场不景气等因素影响，市场需求疲软，开工较少。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>四、未来发展方向及合作意向</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">大力推进供给侧结构性改革，加快矿业结构调整和转型升级，提高大中型矿山占比，强力推进如火山渣、硅藻土等矿产品深加工及下游产业链条发展，增强可持续发展能力，提升经济效益；积极引进资金加大铁、金、矿泉水、建筑石料用灰岩等资源有效开发利用，提升经济效益。</span></p>
<p>&nbsp;</p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
