//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">粮食资源</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、粮食生产情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2020</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年全县粮食播种面积<span lang="EN-US">87726</span>公顷，其中：玉米<span lang="EN-US">65610</span>公顷，稻谷<span lang="EN-US">20180</span>公顷，大豆<span lang="EN-US">1936</span>公顷。主要农作物产量<span lang="EN-US">70</span>万吨，其中：玉米约<span lang="EN-US">55</span>万吨，稻谷约<span lang="EN-US">14</span>万吨，大豆<span lang="EN-US">5500</span>吨。柳河县规模以上粮食收储企业<span lang="EN-US">33</span>户，总仓容<span lang="EN-US">52.5</span>万吨，其中标准仓<span lang="EN-US">11.9</span>万吨。简易仓容<span lang="EN-US">39.6</span>万吨，储粮罩棚<span lang="EN-US">3.7</span>万吨。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">县域内较大的玉米种植以亨通镇、圣水镇尤为突出，种植面积相对较大且集中，约占全县总种植面积的<span lang="EN-US">27%</span>，出产玉米及秸秆品质上乘。向阳镇、红石镇、孤山子镇、三源浦镇、柳南乡在我县玉米种植区中也相对较好，种植相对集中，品质较好。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">水稻种植相对较集中的区域有：姜家店乡、三源浦镇、孤山子镇和圣水镇，三个乡镇约占总量的<span lang="EN-US">35%</span>。其中：姜家店乡生产的水稻品质非常优秀，素有火山岩贡米的美誉，是大米姐、国信、蛙田、芳谷、禾兴等知名柳河大米加工企业的重点水稻种植基地。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、粮食资源概况及优势</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县位于吉林省东南部，有&ldquo;千年古城百年县、一城柳色半城河&rdquo;的美誉。我县贯彻落实习近平总书记关于&ldquo;深入推进优质粮食工程&rdquo;、&ldquo;做好粮食市场和流通的文章&rdquo;的重要指示精神，打造引领现代农业发展的&ldquo;金招牌&rdquo;，挑起农民小康梦的&ldquo;金扁担&rdquo;。柳河县地处世界&ldquo;白金水稻&rdquo;带（北纬<span lang="EN-US">40</span>。～<span lang="EN-US"> 45</span>。）的中间地带（北纬<span lang="EN-US">41</span>。<span lang="EN-US">53</span>ˊ～<span lang="EN-US"> 42</span>。<span lang="EN-US">35</span>ˊ），是世界公认的&ldquo;白金水稻带&rdquo;的中心地带。气候属于温带大陆性季风气候，水稻生育期间气温适宜，秋季水稻灌浆期昼夜温差大，有利于支链淀粉的形成和积累，米质优良。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县境内有一统河、三统河、哈泥河和窝集河<span lang="EN-US">4</span>大水系，总长<span lang="EN-US">389.8</span>公里，流域面积<span lang="EN-US">3348.3</span>平方公里，地表水径流年均总量<span lang="EN-US">11.07</span>亿立方米，可开发水能资源总量<span lang="EN-US">49450</span>千瓦。水源均来自于长白山火山支脉的山间水泉，蕴含长白山山脉火山岩之灵秀精华，富含钾、镁、钼、锌、锶、钴、锗、锂等对作物和人体有益的微量元素，有利于提高稻谷养分。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河在清朝经历了长达数百年的封禁，开发较晚。森林覆盖率达<span lang="EN-US">51%</span>，再加上该县工业污染小，空气符合生产绿优米标准。地下具有丰富的火山岩，在火山熔岩台地上种植水稻，岩石的吸热和散热快，借助石板的热辐射，水的温度高，多孔的玄武石渗水，透气性良好，但却不漏水，排水迅速，便于通风和晒田。这些条件都能促进水稻的扬花、灌浆和早熟。这独特的石板地环境，便是柳河火山岩稻米早熟、饱满、优质、高产的奥秘，也是柳河大米被称为&ldquo;火山岩大米&rdquo;的原因。<span lang="EN-US">2017</span>年柳河县被中国粮食行业协会评为&ldquo;中国火山岩稻米之乡&rdquo;。还具有&ldquo;国家级商品粮基地县&rdquo;称号，常年获得国内多项大奖。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
