//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">林业资源</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、森林资源概况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县位于吉林省东南部山区，是吉林省的重点林区县之一。<span lang="EN-US">2020</span>年，全县森林覆盖率<span lang="EN-US">51%</span>，林木蓄积量<span lang="EN-US">1804</span>万立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）森林面积</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县林地面积<span lang="EN-US">196903</span>公顷，非林地面积<span lang="EN-US">109806.9</span>公顷。其中：有林地面积<span lang="EN-US">153765.04</span>公顷，在有林地面积中纯林面积<span lang="EN-US">54936.94</span>公顷，混交林面积<span lang="EN-US">98828.10</span>公顷；灌木林地面积<span lang="EN-US">3840.44</span>公顷；未成林地面积<span lang="EN-US">5602.03</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">国有林面积为<span lang="EN-US">71831.04</span>公顷，其中：凉水林场<span lang="EN-US">18351.99</span>公顷，八里哨林场<span lang="EN-US">11595.00</span>公顷，全胜林场<span lang="EN-US">2941.69</span>公顷，五道沟林场<span lang="EN-US">8348.49</span>公顷，大北岔林场<span lang="EN-US">11250.56</span>公顷，兰山林场<span lang="EN-US">5355.32</span>公顷，安口镇林场<span lang="EN-US">9452.79</span>公顷，向阳林场<span lang="EN-US">4314.28</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">集体林面积为<span lang="EN-US">81934.00</span>公顷，其中：柳河镇<span lang="EN-US">10069.58</span>公顷，五道沟镇<span lang="EN-US">4203.95</span>公顷，驼腰岭镇<span lang="EN-US">3376.83</span>公顷，安口镇<span lang="EN-US">12158.79</span>公顷，向阳镇<span lang="EN-US">8617.78</span>公顷，红石镇<span lang="EN-US">5761.34</span>公顷，三源浦镇<span lang="EN-US">9929.04</span>公顷，柳南乡<span lang="EN-US">6866.62</span>公顷，孤山子镇<span lang="EN-US">3711.62</span>公顷，时家店乡<span lang="EN-US">4232.69</span>公顷，姜家店乡<span lang="EN-US">1495.26</span>公顷，罗通山镇<span lang="EN-US">4200.37</span>公顷，凉水河子镇<span lang="EN-US">1519.93</span>公顷，圣水镇<span lang="EN-US">3930.15</span>公顷，亨通镇<span lang="EN-US">2080.97</span>公顷。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）林木储量</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县林木总蓄积量<span lang="EN-US">18169194</span>立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">国有林<span lang="EN-US">10306637</span>立方米，其中：凉水林场<span lang="EN-US">2737702</span>立方米，八里哨林场<span lang="EN-US">1603029</span>立方米，全胜林场<span lang="EN-US">352378</span>立方米，五道沟林场<span lang="EN-US">1149841</span>立方米，大北岔林场<span lang="EN-US">1834274</span>立方米，兰山林场<span lang="EN-US">629702</span>立方米，安口镇林场<span lang="EN-US">1398676</span>立方米，向阳林场<span lang="EN-US">601053</span>立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">集体林<span lang="EN-US">7862382</span>立方米，其中：柳河镇<span lang="EN-US">897711</span>立方米，五道沟镇<span lang="EN-US">309837</span>立方米，驼腰岭镇<span lang="EN-US">30019</span>立方米，安口镇<span lang="EN-US">1347473</span>立方米，向阳镇<span lang="EN-US">973406</span>立方米，红石林镇<span lang="EN-US">603795</span>立方米，三源浦镇<span lang="EN-US">960318</span>立方米，柳南乡<span lang="EN-US">699965</span>立方米，孤山子镇<span lang="EN-US">349083</span>立方米，时家店乡<span lang="EN-US">371491</span>立方米，姜家店乡<span lang="EN-US">161725</span>立方米，罗通山镇<span lang="EN-US">407995</span>立方米，凉水河子镇<span lang="EN-US">68117</span>立方米，圣水镇<span lang="EN-US">233966</span>立方米，亨通镇<span lang="EN-US">47638</span>立方米。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县年采伐木材约<span lang="EN-US">20000</span>立方米（采伐限额），其中：国有<span lang="EN-US">8000</span>立方米，集体约<span lang="EN-US">12000</span>立方米。在总出材中，针叶木材约<span lang="EN-US">17000</span>立方米（主要树种为落叶松）， 阔叶木材<span lang="EN-US">3000</span>立方米 （主要树种为柞、楸、杨、桦树等）。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、国有林场整体情况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）资源情况</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">国有林场经营总面积<span lang="EN-US">75749.9</span>公顷。<span lang="EN-US">2020</span>年末，国有林场施业区森林覆盖率<span lang="EN-US">95.06%</span>，国有林场林木蓄积量<span lang="EN-US">1014</span>万立方米。 </span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）人员情况</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">全县共有<span lang="EN-US">8</span>个国有林场，林业职工总数为<span lang="EN-US">2251</span>人，其中：在职职工<span lang="EN-US">1056</span>人，离退休职工<span lang="EN-US">1195</span>人。在职职工中，在岗职工<span lang="EN-US">845</span>人，待岗职工<span lang="EN-US">211</span>人。在岗职工年平均工资约为<span lang="EN-US">26000</span>元，月平均<span lang="EN-US">2160</span>元；待业职工平均年工资<span lang="EN-US">9600</span>元，月平均<span lang="EN-US">800</span>元。职工参保率<span lang="EN-US">100%</span>。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（三）财务情况</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span lang="EN-US" style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">2020</span><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">年末，全县<span lang="EN-US">8</span>个国有林场资产总额为<span lang="EN-US">2.84</span>亿元，其中：流动资产<span lang="EN-US">1.55</span>亿元，林木资产<span lang="EN-US">1.26</span>亿元，负债总额为<span lang="EN-US">1727</span>万元，净资产<span lang="EN-US">2.67</span>亿元。全部固定资产（净值）<span lang="EN-US">2948</span>万元。</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（四）发展趋势</span></p>
<p class="MsoNormal" style="text-indent: 24pt; line-height: 150%; text-align: justify;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">国有林场改革后，森林资源保护已成为国有林场的重要工作，在确保森林资源安全的情况下，大力发展林业特色产业，红松果林、林下参和中草药、养殖业、苗木产业已经成为国有林场的主要发展方向。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
