//create by: 邓志锋 <280160522@qq.com> <https://www.diygw.com> DIYGW可视化设计一键生成源码
Page({
	data: {
		//用户全局信息
		userInfo: {},
		text: `<p style="text-align: center;">水利资源</p>`,
		text1: `<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>一、水资源分布概况</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（一）河流水系情况</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县境内水系发达，流域分布均匀，河网密度大，河流众多，分属鸭绿江流域浑江水系和第二松花江流域辉发河水系。东南部的哈泥河属鸭绿江流域浑江水系，西侧、北侧的一统河和中部的三统河均属第二松花江流域辉发河水系。全县<span lang="EN-US">6</span>级河流中，河长超过<span lang="EN-US">10</span>公里的有<span lang="EN-US">29</span>条，面积超过<span lang="EN-US">20</span>平方公里的有<span lang="EN-US">36</span>条河流、面积超过<span lang="EN-US">50</span>平方公里的有<span lang="EN-US">20</span>条。主要河流有浑江水系的哈泥河和辉发河水系的一统河、三统河、窝集河（一统河支流）等。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">（二）水资源总量及可利用量</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县多年平均降水量为<span lang="EN-US">773.6</span>毫米；多年平均水面蒸发量为<span lang="EN-US">(</span>水面蒸发值<span lang="EN-US">)791.1</span>毫米；多年平均水资源总量为<span lang="EN-US">11.00</span>&times;<span lang="EN-US">108</span>立方米（多年平均径流深<span lang="EN-US">328.8</span>毫米），其中，地表水资源量为<span lang="EN-US">10.99</span>&times;<span lang="EN-US">108</span>立方米，地下水资源量为<span lang="EN-US">2.795</span>&times;<span lang="EN-US">108</span>立方米（与地表水重复计算量为<span lang="EN-US">2.787</span>&times;<span lang="EN-US">108</span>立方米）。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县多年平均地表水资源可利用量为<span lang="EN-US">3.605</span>&times;<span lang="EN-US">108</span>立方米，地下水可开采量为<span lang="EN-US">1.397</span>&times;<span lang="EN-US">108</span>立方米（开采系数采用<span lang="EN-US">0.50</span>），水资源总量可利用量为<span lang="EN-US">3.605</span>&times;<span lang="EN-US">108</span>立方米（可利用量重复计算量<span lang="EN-US">1.397</span>&times;<span lang="EN-US">108</span>立方米）；水资源总量<span lang="EN-US">11.00</span>&times;<span lang="EN-US">108</span>立方米，水资源总量可利用率为<span lang="EN-US">32.8%</span>。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>二、水利发展现状</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">新中国成立以来，柳河县在各级政府的支持和帮助下进行了大规模的水利建设，取得了巨大成就。截止目前，全县共建成各类水利工程<span lang="EN-US">1153</span>项，中型水库<span lang="EN-US">3</span>座，小（Ⅰ）型水库<span lang="EN-US">20</span>座，小（Ⅱ）型水库<span lang="EN-US">78</span>座，塘坝<span lang="EN-US">559</span>座，小型水电站<span lang="EN-US">4</span>座，万亩以上灌区<span lang="EN-US">4</span>处。</span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;"><strong>三、规模以上水库项目</strong></span></p>
<p class="MsoNormal" style="text-indent: 24.0pt; mso-char-indent-count: 2.0; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 宋体; mso-ascii-theme-font: major-fareast; mso-fareast-theme-font: major-fareast; mso-hansi-theme-font: major-fareast;">柳河县安口水库是一座以城镇供水为主的中型水库，于<span lang="EN-US">2015</span>年<span lang="EN-US">3</span>月<span lang="EN-US">12</span>日开工建设<span lang="EN-US">,</span>至<span lang="EN-US">2017</span>年<span lang="EN-US">8</span>月全部完工。水库位于辉发河右岸一级支流一统河上<span lang="EN-US">,</span>库区面积<span lang="EN-US">398.79</span>公顷。坝址位于安口镇南<span lang="EN-US">500</span>米处<span lang="EN-US">,</span>距县城<span lang="EN-US">22.5</span>公里<span lang="EN-US">,</span>控制流域面积<span lang="EN-US">338</span>平方公里<span lang="EN-US">,</span>坝址处多年平均年径流量<span lang="EN-US">8790</span>万立方米。水库坝长<span lang="EN-US">706</span>米<span lang="EN-US">,</span>坝顶高程<span lang="EN-US">400.8</span>米<span lang="EN-US">,</span>坝顶宽<span lang="EN-US">6</span>米。水库总库容<span lang="EN-US">2468</span>万立方米<span lang="EN-US">,</span>正常蓄水库容<span lang="EN-US">1633.5</span>万立方米<span lang="EN-US">,</span>汛限库容<span lang="EN-US">1452</span>万立方米<span lang="EN-US">,</span>兴利库容<span lang="EN-US">1212</span>万立方米<span lang="EN-US">,</span>死库容<span lang="EN-US">421.5</span>万立方米。水库死水位<span lang="EN-US">393.50</span>米<span lang="EN-US">,</span>汛限水位<span lang="EN-US">398.00</span>米<span lang="EN-US">,</span>正常高水位<span lang="EN-US">398.50</span>米<span lang="EN-US">,</span>设计水位<span lang="EN-US">398.00</span>米<span lang="EN-US">,</span>校核水位<span lang="EN-US">400.42</span>米。正常设计日供水量<span lang="EN-US">3.6</span>万吨<span lang="EN-US">(</span>其中县城日供水量<span lang="EN-US">3.0</span>万吨<span lang="EN-US">,</span>安口镇日供水量<span lang="EN-US">0.6</span>万吨<span lang="EN-US">) ,</span>与柳河水库联合调水日供水能力可达<span lang="EN-US">5</span>万吨以上<span lang="EN-US">,</span>可满足未来县城<span lang="EN-US">20</span>万人生产生活用水，水库设计灌溉面积为<span lang="EN-US">5700</span>亩。水库周边及下游可依托水库水利资源开展旅游、娱乐等项目建设。</span></p>`
	},
	onLoad(option) {
		this.init();
	},
	onShareAppMessage() {},
	onShareTimeline() {},
	onShow() {},
	async init() {}
});
